import type { FetchTranscriptResponse, ResolveTranscriptResponse } from "@/types/api";
import { AppError } from "@/server/errors";
import type { RequestLogger } from "@/server/logger";
import { parseTranscriptPayload } from "@/server/youtube/segments";
import { parseTrackToken } from "@/server/youtube/trackToken";
import { buildTrackSummaries, type CaptionTrack } from "@/server/youtube/tracks";
import { parseStrictYouTubeVideoId } from "@/server/youtube/url";
import { fetchCaptionPayload, fetchInnertubePlayer } from "@/server/youtube/watchPage";

type PlayerResponse = {
  videoDetails?: {
    title?: string;
    lengthSeconds?: string;
    thumbnail?: {
      thumbnails?: Array<{ url?: string }>;
    };
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
};

function asPlayerResponse(data: unknown): PlayerResponse {
  if (typeof data !== "object" || data === null) {
    throw new AppError("Unable to parse YouTube player metadata", 502);
  }
  return data as PlayerResponse;
}

function parseDurationSec(value: string | undefined): number | undefined {
  const parsed = Number.parseInt(value ?? "", 10);
  if (Number.isFinite(parsed) && parsed > 0) {
    return parsed;
  }
  return undefined;
}

function buildCandidateUrls(baseUrl: string): string[] {
  const candidateUrls = new Set<string>([baseUrl]);

  let parsed: URL;
  try {
    parsed = new URL(baseUrl);
  } catch {
    return Array.from(candidateUrls);
  }

  // Keep an exact replay candidate first, then try normalized variations.
  candidateUrls.add(parsed.toString());

  // Try multiple caption formats because YouTube can expose track data
  // under different `fmt` values for different videos/locales.
  for (const fmt of ["json3", "vtt", "ttml", "srv3", "srv1"]) {
    const withFmt = new URL(parsed);
    withFmt.searchParams.set("fmt", fmt);
    candidateUrls.add(withFmt.toString());
  }

  const raw = new URL(parsed);
  raw.searchParams.delete("fmt");
  candidateUrls.add(raw.toString());

  return Array.from(candidateUrls);
}

function summarizeCaptionUrl(url: string): Record<string, unknown> {
  const parsed = new URL(url);
  return {
    host: parsed.hostname,
    path: parsed.pathname,
    fmt: parsed.searchParams.get("fmt"),
    lang: parsed.searchParams.get("lang"),
    kind: parsed.searchParams.get("kind")
  };
}

export async function fetchTranscriptMetadata(params: {
  url: string;
  preferredLanguage: string;
  timeoutMs: number;
  trackTokenSecret: string;
  trackTokenTtlSeconds: number;
  logger?: RequestLogger;
}): Promise<FetchTranscriptResponse> {
  const { url, preferredLanguage, timeoutMs, trackTokenSecret, trackTokenTtlSeconds, logger } = params;
  logger?.debug("youtube.fetch_metadata.start", { url, preferredLanguage });

  const videoId = parseStrictYouTubeVideoId(url);
  if (!videoId) {
    throw new AppError("Only single YouTube video URLs are supported", 422);
  }

  const innertubeData = await fetchInnertubePlayer(videoId, timeoutMs, logger);
  const playerResponse = asPlayerResponse(innertubeData);
  const rawTracks = playerResponse.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  if (rawTracks.length === 0) {
    throw new AppError("No caption tracks available for this video", 404);
  }

  logger?.debug("youtube.fetch_metadata.track_candidates", {
    videoId,
    trackCount: rawTracks.length
  });

  const { tracks, defaultTrackToken } = buildTrackSummaries({
    videoId,
    rawTracks,
    preferredLanguage,
    tokenSecret: trackTokenSecret,
    tokenTtlSeconds: trackTokenTtlSeconds
  });

  const durationSec = parseDurationSec(playerResponse.videoDetails?.lengthSeconds);
  const thumbnails = playerResponse.videoDetails?.thumbnail?.thumbnails ?? [];
  const thumbnailUrl = [...thumbnails].reverse().find((item) => typeof item.url === "string" && item.url)?.url;
  const defaultTrack = tracks.find((track) => track.token === defaultTrackToken);

  logger?.debug("youtube.fetch_metadata.success", {
    videoId,
    trackCount: tracks.length,
    defaultLanguageCode: defaultTrack?.languageCode,
    defaultIsAutoGenerated: defaultTrack?.isAutoGenerated ?? false
  });

  return {
    videoId,
    title: playerResponse.videoDetails?.title ?? `YouTube ${videoId}`,
    durationSec,
    thumbnailUrl,
    tracks,
    defaultTrackToken
  };
}

export async function resolveTranscriptSegments(params: {
  videoId: string;
  trackToken: string;
  timeoutMs: number;
  trackTokenSecret: string;
  logger?: RequestLogger;
}): Promise<ResolveTranscriptResponse> {
  const { videoId, trackToken, timeoutMs, trackTokenSecret, logger } = params;
  logger?.debug("youtube.resolve_segments.start", {
    videoId,
    trackTokenPrefix: trackToken.slice(0, 10)
  });

  const payload = parseTrackToken(trackToken, trackTokenSecret);
  if (payload.videoId !== videoId) {
    throw new AppError("Track token does not belong to the provided video", 400);
  }

  logger?.debug("youtube.resolve_segments.track_token", {
    videoIdFromToken: payload.videoId,
    languageCode: payload.languageCode,
    isAutoGenerated: payload.isAutoGenerated,
    expiresAt: payload.expiresAt
  });

  const candidateUrls = buildCandidateUrls(payload.baseUrl);
  logger?.info("youtube.resolve_segments.base_url", {
    videoId,
    baseUrl: payload.baseUrl
  });
  logger?.debug("youtube.resolve_segments.candidates", {
    candidateCount: candidateUrls.length,
    candidates: candidateUrls.map((url) => summarizeCaptionUrl(url))
  });

  let lastFetchError: AppError | null = null;
  let sawParsedPayload = false;
  let sawUnsupportedPayload = false;

  for (const [index, candidateUrl] of candidateUrls.entries()) {
    let rawPayload = "";
    const attempt = index + 1;
    const candidateMeta = summarizeCaptionUrl(candidateUrl);
    logger?.debug("youtube.resolve_segments.fetch_attempt", {
      attempt,
      ...candidateMeta
    });

    try {
      rawPayload = await fetchCaptionPayload(candidateUrl, timeoutMs, logger, {
        attempt,
        ...candidateMeta
      });
    } catch (error) {
      if (error instanceof AppError) {
        lastFetchError = error;
        logger?.warn("youtube.resolve_segments.fetch_failed", {
          attempt,
          ...candidateMeta,
          statusCode: error.statusCode,
          message: error.message
        });
        continue;
      }
      throw error;
    }

    const { parsed, segments } = parseTranscriptPayload(rawPayload);
    logger?.debug("youtube.resolve_segments.parse_result", {
      attempt,
      ...candidateMeta,
      parsed,
      segmentCount: segments.length
    });

    if (!parsed) {
      sawUnsupportedPayload = true;
      continue;
    }

    sawParsedPayload = true;
    if (segments.length === 0) {
      continue;
    }

    logger?.debug("youtube.resolve_segments.success", {
      videoId,
      languageCode: payload.languageCode,
      isAutoGenerated: payload.isAutoGenerated,
      segmentCount: segments.length
    });

    return {
      videoId,
      track: {
        token: trackToken,
        languageCode: payload.languageCode,
        label: payload.label,
        isAutoGenerated: payload.isAutoGenerated
      },
      segments
    };
  }

  if (lastFetchError && !sawParsedPayload) {
    logger?.warn("youtube.resolve_segments.abort_last_fetch_error", {
      videoId,
      statusCode: lastFetchError.statusCode,
      message: lastFetchError.message
    });
    throw lastFetchError;
  }

  if (sawParsedPayload) {
    logger?.warn("youtube.resolve_segments.empty_content", {
      videoId,
      languageCode: payload.languageCode
    });
    throw new AppError("Caption content is empty", 404);
  }

  if (sawUnsupportedPayload) {
    logger?.warn("youtube.resolve_segments.unsupported_payload", { videoId });
    throw new AppError("Caption parsing failed: unsupported payload format", 502);
  }

  logger?.error("youtube.resolve_segments.parsing_failed", { videoId });
  throw new AppError("Caption parsing failed", 502);
}
