import type { TrackSummary } from "@/types/api";
import { createTrackToken } from "@/server/youtube/trackToken";

type CaptionName = {
  simpleText?: string;
  runs?: Array<{ text?: string }>;
};

export type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  name?: CaptionName;
  kind?: string;
};

function getLanguageLabel(name: CaptionName | undefined, fallback: string): string {
  if (!name) {
    return fallback;
  }

  if (name.simpleText && name.simpleText.trim()) {
    return name.simpleText.trim();
  }

  if (Array.isArray(name.runs)) {
    const merged = name.runs.map((item) => item.text ?? "").join("").trim();
    if (merged) {
      return merged;
    }
  }

  return fallback;
}

export function buildTrackSummaries(params: {
  videoId: string;
  rawTracks: CaptionTrack[];
  preferredLanguage: string;
  tokenSecret: string;
  tokenTtlSeconds: number;
}): { tracks: TrackSummary[]; defaultTrackToken: string } {
  const { videoId, rawTracks, preferredLanguage, tokenSecret, tokenTtlSeconds } = params;

  const tracks = rawTracks.map((track) => {
    const languageCode = track.languageCode;
    const isAutoGenerated = track.kind === "asr";
    const label = getLanguageLabel(track.name, languageCode);

    return {
      token: createTrackToken(
        {
          videoId,
          baseUrl: track.baseUrl,
          languageCode,
          label,
          isAutoGenerated
        },
        tokenSecret,
        tokenTtlSeconds
      ),
      languageCode,
      label,
      isAutoGenerated
    } satisfies TrackSummary;
  });

  const preferred = preferredLanguage.toLowerCase();
  tracks.sort((a, b) => {
    const aPreferred = a.languageCode.toLowerCase().startsWith(preferred) ? 1 : 0;
    const bPreferred = b.languageCode.toLowerCase().startsWith(preferred) ? 1 : 0;
    if (aPreferred !== bPreferred) {
      return bPreferred - aPreferred;
    }

    if (a.isAutoGenerated !== b.isAutoGenerated) {
      return Number(a.isAutoGenerated) - Number(b.isAutoGenerated);
    }

    return a.label.localeCompare(b.label);
  });

  const defaultTrackToken =
    tracks.find((track) => track.languageCode.toLowerCase().startsWith(preferred) && !track.isAutoGenerated)?.token ||
    tracks.find((track) => track.languageCode.toLowerCase().startsWith(preferred) && track.isAutoGenerated)?.token ||
    tracks.find((track) => track.languageCode.startsWith("en") && !track.isAutoGenerated)?.token ||
    tracks.find((track) => !track.isAutoGenerated)?.token ||
    tracks[0]?.token ||
    "";

  return {
    tracks,
    defaultTrackToken
  };
}
