import { createHmac, timingSafeEqual } from "node:crypto";
import { TrackTokenExpiredError, TrackTokenInvalidError } from "@/server/errors";

const ALLOWED_CAPTION_HOSTS = new Set([
  "youtube.com",
  "www.youtube.com",
  "m.youtube.com",
  "youtube-nocookie.com",
  "www.youtube-nocookie.com"
]);

export type TrackTokenPayload = {
  videoId: string;
  baseUrl: string;
  languageCode: string;
  label: string;
  isAutoGenerated: boolean;
  issuedAt: number;
  expiresAt: number;
};

type UnsignedPayload = Omit<TrackTokenPayload, "issuedAt" | "expiresAt">;

function encodePayload(payload: TrackTokenPayload): string {
  return Buffer.from(JSON.stringify(payload), "utf8").toString("base64url");
}

function decodePayload(encoded: string): TrackTokenPayload {
  try {
    const raw = Buffer.from(encoded, "base64url").toString("utf8");
    const parsed = JSON.parse(raw) as Partial<TrackTokenPayload>;

    if (
      typeof parsed.videoId !== "string" ||
      typeof parsed.baseUrl !== "string" ||
      typeof parsed.languageCode !== "string" ||
      typeof parsed.label !== "string" ||
      typeof parsed.isAutoGenerated !== "boolean" ||
      typeof parsed.issuedAt !== "number" ||
      typeof parsed.expiresAt !== "number"
    ) {
      throw new Error("invalid token payload");
    }

    return parsed as TrackTokenPayload;
  } catch {
    throw new TrackTokenInvalidError("malformed_payload");
  }
}

function signValue(value: string, secret: string): string {
  return createHmac("sha256", secret).update(value).digest("base64url");
}

function normalizeCaptionUrl(baseUrl: string): string {
  const trimmed = baseUrl.trim();

  let parsed: URL;
  try {
    parsed = new URL(trimmed);
  } catch {
    throw new TrackTokenInvalidError("invalid_url");
  }

  const host = parsed.hostname.toLowerCase();
  if (parsed.protocol !== "https:" || !ALLOWED_CAPTION_HOSTS.has(host)) {
    throw new TrackTokenInvalidError("disallowed_host");
  }

  if (!parsed.pathname.startsWith("/api/timedtext")) {
    throw new TrackTokenInvalidError("invalid_path");
  }

  // Preserve the original URL text so signed query parameters are not rewritten.
  return trimmed;
}

export function createTrackToken(payload: UnsignedPayload, secret: string, ttlSeconds: number): string {
  const now = Date.now();
  const normalized: TrackTokenPayload = {
    ...payload,
    baseUrl: normalizeCaptionUrl(payload.baseUrl),
    issuedAt: now,
    expiresAt: now + ttlSeconds * 1000
  };

  const encoded = encodePayload(normalized);
  const signature = signValue(encoded, secret);
  return `${encoded}.${signature}`;
}

export function parseTrackToken(token: string, secret: string, nowMs = Date.now()): TrackTokenPayload {
  const [encoded, signature] = token.split(".");
  if (!encoded || !signature) {
    throw new TrackTokenInvalidError("malformed_token");
  }

  const expectedSignature = signValue(encoded, secret);
  const providedBuffer = Buffer.from(signature);
  const expectedBuffer = Buffer.from(expectedSignature);
  if (
    providedBuffer.length !== expectedBuffer.length ||
    !timingSafeEqual(providedBuffer, expectedBuffer)
  ) {
    throw new TrackTokenInvalidError("bad_signature");
  }

  const payload = decodePayload(encoded);
  payload.baseUrl = normalizeCaptionUrl(payload.baseUrl);

  if (nowMs > payload.expiresAt) {
    throw new TrackTokenExpiredError();
  }

  return payload;
}
