export interface CaptionTrackLike {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string; runs?: Array<{ text?: string }> };
  vssId?: string;
}

export interface PlayerResponseLike {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrackLike[];
    };
  };
  videoDetails?: {
    videoId?: string;
    title?: string;
    thumbnail?: { thumbnails?: Array<{ url?: string }> };
  };
}

export interface TrackSummaryEntry {
  trackIndex: number;
  languageCode: string;
  label: string;
  isAutoGenerated: boolean;
}

export interface PlayerSummary {
  video: { videoId: string; title: string; thumbnailUrl: string };
  tracks: TrackSummaryEntry[];
}

export declare function readPlayerResponse(windowLike: unknown): PlayerResponseLike | null;
export declare function hasUsableCaptionTracks(value: unknown): boolean;
export declare function chooseCaptionTrack(
  tracks: CaptionTrackLike[] | null | undefined,
  options?: { preferredLanguage?: string },
): CaptionTrackLike | null;
export declare function summarizeTracks(playerResponse: unknown): PlayerSummary;
export declare function buildDownloadFilename(input: {
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
}): string;
export declare function parseTimestampToMs(value: unknown): number;
export declare function readStartMsFromRow(row: unknown): number | null;
export declare function readEndMsFromRow(row: unknown): number | null;
