import { buildTrackId, mapSegments, mapTracks } from "@/features/storage/repository";
import type { SegmentDTO, TrackSummary } from "@/types/api";
import type { SegmentRecord, TrackRecord, VideoRecord } from "@/types/models";
import { z } from "zod";

const extensionImportSegmentSchema = z
  .object({
    startMs: z.number().int().nonnegative(),
    endMs: z.number().int().positive(),
    text: z.string().trim().min(1),
  })
  .refine((segment) => segment.endMs > segment.startMs, {
    message: "Segment end must be greater than start.",
    path: ["endMs"],
  });

const extensionImportPayloadSchema = z.object({
  version: z.literal(1),
  source: z.literal("shadowing-space-extension"),
  exportedAt: z.string().datetime(),
  video: z.object({
    videoId: z.string().trim().length(11),
    title: z.string().trim().min(1),
    thumbnailUrl: z.string().trim().url().optional(),
  }),
  track: z.object({
    languageCode: z.string().trim().min(1),
    label: z.string().trim().min(1),
    isAutoGenerated: z.boolean(),
    originTrackId: z.string().trim().min(1).optional(),
  }),
  segments: z.array(extensionImportSegmentSchema).min(1),
});

const extensionImportMessageSchema = z.object({
  type: z.literal("shadowing-space-extension/import"),
  payload: extensionImportPayloadSchema,
});

export type ExtensionImportPayload = z.infer<typeof extensionImportPayloadSchema>;

function normalizeTokenPart(value: string | undefined, fallback: string): string {
  const normalized = (value ?? "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

  return normalized || fallback;
}

export function buildExtensionTrackToken(
  track: Pick<ExtensionImportPayload["track"], "languageCode" | "isAutoGenerated" | "originTrackId" | "label">,
): string {
  const languageCode = normalizeTokenPart(track.languageCode, "unknown");
  const mode = track.isAutoGenerated ? "auto" : "manual";
  const originTrackId = normalizeTokenPart(track.originTrackId ?? track.label, "default");

  return `ext-v1:${languageCode}:${mode}:${originTrackId}`;
}

export function parseExtensionImportMessage(data: unknown): ExtensionImportPayload | null {
  const parsed = extensionImportMessageSchema.safeParse(data);
  return parsed.success ? parsed.data.payload : null;
}

export function createImportBundleFromExtensionPayload(
  input: unknown,
  createdAt: number = Date.now(),
): {
  video: VideoRecord;
  tracks: TrackRecord[];
  targetTrackId: string;
  segments: SegmentRecord[];
} {
  const parsed = extensionImportPayloadSchema.safeParse(input);
  if (!parsed.success) {
    throw new Error("Invalid extension import payload.");
  }

  const payload = parsed.data;
  const token = buildExtensionTrackToken(payload.track);
  const track: TrackSummary = {
    token,
    languageCode: payload.track.languageCode.trim(),
    label: payload.track.label.trim(),
    isAutoGenerated: payload.track.isAutoGenerated,
  };

  const sortedSegments: SegmentDTO[] = [...payload.segments]
    .sort((left, right) => left.startMs - right.startMs || left.endMs - right.endMs)
    .map((segment, index) => ({
      index,
      startMs: segment.startMs,
      endMs: segment.endMs,
      text: segment.text.trim(),
    }));

  const video: VideoRecord = {
    id: payload.video.videoId,
    youtubeVideoId: payload.video.videoId,
    title: payload.video.title.trim(),
    thumbnailUrl: payload.video.thumbnailUrl?.trim(),
    createdAt,
  };

  const tracks = mapTracks(payload.video.videoId, [track], createdAt);
  const targetTrackId = buildTrackId(payload.video.videoId, token);
  const segments = mapSegments(targetTrackId, sortedSegments);

  return {
    video,
    tracks,
    targetTrackId,
    segments,
  };
}
