import { resolveImportEndpoint } from "./lib/endpoint.js";
import { buildDownloadFilename } from "./lib/player-response.js";
import { createEnvelope, HANDOFF_STORAGE_KEY } from "./lib/handoff.js";

const LOG_PREFIX = "[SS]";
const MESSAGE_LIST_TRACKS = "shadowing-space-extension/list-tracks";
const MESSAGE_EXTRACT_TRACK = "shadowing-space-extension/extract-track";

const els = {
  status: document.getElementById("status"),
  log: document.getElementById("log-output"),
  logSummary: document.getElementById("log-summary"),
  videoBlock: document.getElementById("video-block"),
  videoTitle: document.getElementById("video-title"),
  videoId: document.getElementById("video-id"),
  videoThumbnail: document.getElementById("video-thumbnail"),
  tracksSection: document.getElementById("tracks-section"),
  trackList: document.getElementById("track-list"),
  actionsSection: document.getElementById("actions-section"),
  sendBtn: document.getElementById("send-btn"),
  downloadBtn: document.getElementById("download-btn"),
  openOptions: document.getElementById("open-options"),
};

const logEntries = [];

function appendLog(level, message, detail) {
  const timestamp = new Date().toISOString().slice(11, 23);
  const line =
    detail !== undefined
      ? `${timestamp} ${level.toUpperCase()} ${message} ${JSON.stringify(detail)}`
      : `${timestamp} ${level.toUpperCase()} ${message}`;
  logEntries.push(line);
  els.log.textContent = logEntries.join("\n");
  els.logSummary.textContent = `Debug log (${logEntries.length})`;
  if (level === "error") console.error(LOG_PREFIX, message, detail ?? "");
  else if (level === "warn") console.warn(LOG_PREFIX, message, detail ?? "");
  else console.log(LOG_PREFIX, message, detail ?? "");
}

function setStatus(kind, text) {
  els.status.className = `status ${kind}`;
  els.status.textContent = text;
}

function showError(text, detail) {
  setStatus("error", text);
  appendLog("error", text, detail);
}

function showInfo(text, detail) {
  setStatus("", text);
  appendLog("info", text, detail);
}

function showOk(text, detail) {
  setStatus("ok", text);
  appendLog("info", text, detail);
}

function showWarn(text, detail) {
  setStatus("warning", text);
  appendLog("warn", text, detail);
}

async function getActiveTab() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  if (!tab || !tab.id) throw new Error("No active tab found.");
  return tab;
}

function isYouTubeWatchUrl(url) {
  return typeof url === "string" && /^https:\/\/www\.youtube\.com\/watch\b/i.test(url);
}

async function sendToTab(tabId, message) {
  appendLog("debug", "sendToTab", { tabId, type: message?.type });
  try {
    return await chrome.tabs.sendMessage(tabId, message);
  } catch (error) {
    throw new Error(
      `Content script unreachable (${error?.message ?? error}). Try refreshing the YouTube tab.`,
    );
  }
}

function clearChildren(node) {
  while (node.firstChild) node.removeChild(node.firstChild);
}

function renderTracks(summary) {
  clearChildren(els.trackList);

  if (summary.tracks.length === 0) {
    els.tracksSection.hidden = false;
    const note = document.createElement("div");
    note.className = "note";
    note.textContent = "No caption tracks found on this video.";
    els.trackList.append(note);
    els.actionsSection.hidden = true;
    return;
  }

  // Prefer manual English, else first track.
  const preferred =
    summary.tracks.find(
      (track) => /^en(?:-|$)/i.test(track.languageCode) && !track.isAutoGenerated,
    ) ?? summary.tracks[0];

  summary.tracks.forEach((track) => {
    const id = `track-${track.trackIndex}`;
    const label = document.createElement("label");
    label.className = "track-item";
    label.setAttribute("for", id);

    const radio = document.createElement("input");
    radio.type = "radio";
    radio.name = "track";
    radio.id = id;
    radio.value = String(track.trackIndex);
    radio.checked = track.trackIndex === preferred?.trackIndex;

    const span = document.createElement("span");
    span.className = "track-item-label";
    span.textContent = track.label;

    const lang = document.createElement("span");
    lang.className = "track-item-lang";
    lang.textContent = track.languageCode;

    label.append(radio, span, lang);

    if (track.isAutoGenerated) {
      const auto = document.createElement("span");
      auto.className = "badge-auto";
      auto.textContent = "auto";
      label.append(auto);
    }

    els.trackList.append(label);
  });

  els.tracksSection.hidden = false;
  els.actionsSection.hidden = false;
}

function getSelectedTrackIndex() {
  const checked = els.trackList.querySelector('input[name="track"]:checked');
  if (!checked) return null;
  const value = Number.parseInt(checked.value, 10);
  return Number.isFinite(value) ? value : null;
}

async function extractSelectedTrack(tabId) {
  const trackIndex = getSelectedTrackIndex();
  if (trackIndex === null) {
    throw new Error("No track selected.");
  }
  appendLog("info", "Extracting track", { trackIndex });
  const response = await sendToTab(tabId, {
    type: MESSAGE_EXTRACT_TRACK,
    trackIndex,
  });
  if (response?.debug?.attempts) {
    response.debug.attempts.forEach((attempt) => {
      appendLog(
        attempt.parsed?.startsWith("json3") || attempt.parsed?.startsWith("xml") ? "info" : "warn",
        `fetch ${attempt.variant}`,
        attempt,
      );
    });
  }
  if (!response?.ok || !response.payload) {
    throw new Error(response?.error || "Extraction failed without a reason.");
  }
  const source = response.debug?.source ?? "fetch";
  const precision = response.debug?.precisionCounts;
  appendLog("info", "Extraction complete", {
    segments: response.payload.segments?.length ?? 0,
    languageCode: response.payload.track?.languageCode,
    source,
    precision,
  });
  if (source === "dom" || source === "dom-prefetch") {
    appendLog("info", "Captions read from YouTube's on-page transcript panel.", {
      fetchError: response.debug?.fetchError,
    });
  }
  if (precision && precision.text > 0 && precision["polymer-ms"] === 0) {
    appendLog(
      "warn",
      `⚠ ${precision.text} segment(s) used second-precision timestamps (rounded to nearest second). Shadowing may drift ±500ms. This happens when YouTube's internal data can't be accessed.`,
    );
  }
  return response.payload;
}

async function deliverToImportTab(payload) {
  const settings = await chrome.storage.sync.get(["mode", "customUrl"]);
  const endpoint = resolveImportEndpoint(settings);

  // Stash the payload in chrome.storage.local. The destination page's bridge
  // content script reads this on load and posts it into the React app, which
  // means the popup is free to close immediately when the new tab takes focus.
  const envelope = createEnvelope(payload);
  await chrome.storage.local.set({ [HANDOFF_STORAGE_KEY]: envelope });
  appendLog("info", "Payload stashed for handoff", {
    endpoint,
    segments: payload.segments?.length ?? 0,
  });

  await chrome.tabs.create({ url: endpoint, active: true });
  appendLog("info", "Import tab opened — popup will close, bridge takes over.", { endpoint });
}

function downloadPayload(payload) {
  const json = JSON.stringify(payload, null, 2);
  const filename = buildDownloadFilename({
    videoId: payload.video?.videoId ?? "",
    languageCode: payload.track?.languageCode ?? "",
    isAutoGenerated: Boolean(payload.track?.isAutoGenerated),
  });

  // Using data URL keeps this entirely within the popup (no blob cleanup to worry about).
  const url = `data:application/json;charset=utf-8,${encodeURIComponent(json)}`;
  appendLog("info", "Triggering download", { filename, sizeBytes: json.length });

  return new Promise((resolve, reject) => {
    chrome.downloads.download({ url, filename, saveAs: true }, (downloadId) => {
      if (chrome.runtime.lastError) {
        reject(new Error(chrome.runtime.lastError.message));
        return;
      }
      appendLog("info", "Download started", { downloadId });
      resolve(downloadId);
    });
  });
}

async function init() {
  els.openOptions.addEventListener("click", (event) => {
    event.preventDefault();
    chrome.runtime.openOptionsPage();
  });

  els.sendBtn.addEventListener("click", async () => {
    els.sendBtn.disabled = true;
    els.downloadBtn.disabled = true;
    try {
      const tab = await getActiveTab();
      showInfo("Extracting transcript…");
      const payload = await extractSelectedTrack(tab.id);
      showInfo("Delivering to Shadowing Space…");
      await deliverToImportTab(payload);
      showOk("Sent! Shadowing Space should redirect into practice shortly.");
    } catch (error) {
      showError(error?.message ?? String(error), { stack: error?.stack });
    } finally {
      els.sendBtn.disabled = false;
      els.downloadBtn.disabled = false;
    }
  });

  els.downloadBtn.addEventListener("click", async () => {
    els.sendBtn.disabled = true;
    els.downloadBtn.disabled = true;
    try {
      const tab = await getActiveTab();
      showInfo("Extracting transcript…");
      const payload = await extractSelectedTrack(tab.id);
      await downloadPayload(payload);
      showOk("Download dialog opened.");
    } catch (error) {
      showError(error?.message ?? String(error), { stack: error?.stack });
    } finally {
      els.sendBtn.disabled = false;
      els.downloadBtn.disabled = false;
    }
  });

  let tab;
  try {
    tab = await getActiveTab();
  } catch (error) {
    showError(error?.message ?? String(error));
    return;
  }

  appendLog("info", "Active tab", { url: tab.url, id: tab.id });

  if (!isYouTubeWatchUrl(tab.url)) {
    showWarn("Open a YouTube watch page first, then click the Shadowing Space icon again.");
    return;
  }

  showInfo("Reading caption tracks…");
  try {
    const response = await sendToTab(tab.id, { type: MESSAGE_LIST_TRACKS });
    if (!response?.ok || !response.summary) {
      throw new Error(response?.error || "Could not read caption tracks.");
    }
    const summary = response.summary;
    appendLog("info", "Tracks found", {
      videoId: summary.video.videoId,
      trackCount: summary.tracks.length,
    });

    els.videoTitle.textContent = summary.video.title || "(no title)";
    els.videoId.textContent = summary.video.videoId || "(no id)";
    if (summary.video.thumbnailUrl) {
      els.videoThumbnail.src = summary.video.thumbnailUrl;
      els.videoThumbnail.hidden = false;
    } else {
      els.videoThumbnail.hidden = true;
    }
    els.videoBlock.hidden = false;

    renderTracks(summary);

    if (summary.tracks.length === 0) {
      showWarn("This video has no caption tracks.");
    } else {
      showInfo(`Ready. ${summary.tracks.length} track(s) available.`);
    }
  } catch (error) {
    showError(error?.message ?? String(error), { stack: error?.stack });
  }
}

void init();
