// Main-world content script: runs inside https://www.youtube.com/watch pages and
// reads the Innertube player data the page already hydrated.
//
// MV3 manifest-declared content scripts cannot `import`, so the pure helper logic
// is duplicated here; the canonical version lives in extension/lib/player-response.js
// and is exercised by unit tests. Keep them in sync.
(function () {
  const LIST_REQUEST_EVENT = "shadowing-space-extension:list-request";
  const EXTRACT_REQUEST_EVENT = "shadowing-space-extension:extract-request";
  const LIST_RESULT_TYPE = "shadowing-space-extension/list-result";
  const EXTRACT_RESULT_TYPE = "shadowing-space-extension/extract-result";

  function isPlainObject(value) {
    return typeof value === "object" && value !== null && !Array.isArray(value);
  }

  function tryParseJson(value) {
    if (typeof value !== "string") return null;
    try {
      const parsed = JSON.parse(value);
      return isPlainObject(parsed) ? parsed : null;
    } catch {
      return null;
    }
  }

  function readPlayerResponse() {
    const initial = window.ytInitialPlayerResponse;
    if (isPlainObject(initial)) return initial;

    const args = window.ytplayer?.config?.args;
    if (isPlainObject(args)) {
      if (isPlainObject(args.raw_player_response)) return args.raw_player_response;
      const parsed = tryParseJson(args.player_response);
      if (parsed) return parsed;
    }

    try {
      const flexy = document.querySelector("ytd-watch-flexy");
      const flexyResponse =
        flexy?.playerData?.playerResponse ?? flexy?.__data?.playerData?.playerResponse;
      if (isPlainObject(flexyResponse)) return flexyResponse;
    } catch {
      // querySelector can throw for custom elements before definition; ignore.
    }

    return null;
  }

  function getVideoIdFromLocation() {
    try {
      return new URL(window.location.href).searchParams.get("v") || null;
    } catch {
      return null;
    }
  }

  function labelFromName(name, fallback) {
    if (!name) return fallback;
    if (typeof name.simpleText === "string" && name.simpleText.trim()) {
      return name.simpleText.trim();
    }
    if (Array.isArray(name.runs)) {
      const merged = name.runs
        .map((item) => item?.text ?? "")
        .join("")
        .trim();
      if (merged) return merged;
    }
    return fallback;
  }

  function normalizeText(raw) {
    return raw.replace(/\r?\n/g, " ").replace(/\s+/g, " ").trim();
  }

  // HTML entity decoding without innerHTML — parses as HTML document and reads
  // textContent, which never executes inline scripts. Second pass handles the
  // nested encoding YouTube emits.
  function decodeHtml(value) {
    if (typeof value !== "string" || !value) return "";
    const parser = new DOMParser();
    const first = parser.parseFromString(value, "text/html").documentElement.textContent ?? "";
    if (!first.includes("&")) return first;
    return parser.parseFromString(first, "text/html").documentElement.textContent ?? first;
  }

  function getThumbnailUrl(videoDetails) {
    const thumbnails = Array.isArray(videoDetails?.thumbnail?.thumbnails)
      ? videoDetails.thumbnail.thumbnails
      : [];
    return (
      [...thumbnails].reverse().find((entry) => typeof entry?.url === "string" && entry.url)?.url ??
      ""
    );
  }

  function buildSummary(playerResponse) {
    const videoDetails = isPlainObject(playerResponse?.videoDetails)
      ? playerResponse.videoDetails
      : {};
    const rawTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    const tracks = Array.isArray(rawTracks)
      ? rawTracks.map((track, index) => ({
          trackIndex: index,
          languageCode: typeof track?.languageCode === "string" ? track.languageCode : "",
          label: labelFromName(track?.name, track?.languageCode ?? `Track ${index + 1}`),
          isAutoGenerated: track?.kind === "asr",
        }))
      : [];
    return {
      video: {
        videoId: typeof videoDetails.videoId === "string" ? videoDetails.videoId : "",
        title: typeof videoDetails.title === "string" ? videoDetails.title : "",
        thumbnailUrl: getThumbnailUrl(videoDetails),
      },
      tracks,
    };
  }

  function parseJson3Segments(payloadText) {
    const payload = JSON.parse(payloadText);
    if (!Array.isArray(payload.events)) return [];

    return payload.events
      .filter((event) => Array.isArray(event.segs) && event.tStartMs !== undefined)
      .map((event) => {
        const startMs = Number(event.tStartMs);
        const durationMs = Number(event.dDurationMs ?? 0);
        const text = normalizeText(
          event.segs.map((segment) => decodeHtml(segment.utf8 ?? segment.text ?? "")).join(""),
        );

        return {
          startMs,
          endMs: startMs + Math.max(durationMs || 1_600, 200),
          text,
        };
      })
      .filter(
        (segment) =>
          Number.isFinite(segment.startMs) && segment.endMs > segment.startMs && segment.text,
      );
  }

  function readRowData(row) {
    if (!row || typeof row !== "object") return null;
    return row.data ?? row.__data ?? row._data ?? null;
  }

  function toFiniteNumber(value) {
    if (value == null) return null;
    const n = typeof value === "number" ? value : Number.parseInt(String(value), 10);
    return Number.isFinite(n) ? n : null;
  }

  function readStartMsFromRow(row) {
    const data = readRowData(row);
    if (!data) return null;
    const nested = data.transcriptSegmentRenderer;
    const candidates = [
      data.startMs,
      nested?.startMs,
      data.cueGroupStartOffsetMs,
      nested?.cueGroupStartOffsetMs,
    ];
    for (const value of candidates) {
      const ms = toFiniteNumber(value);
      if (ms !== null) return ms;
    }
    return null;
  }

  function readEndMsFromRow(row) {
    const data = readRowData(row);
    if (!data) return null;
    const nested = data.transcriptSegmentRenderer;
    const directEnd = toFiniteNumber(data.endMs ?? nested?.endMs);
    if (directEnd !== null) return directEnd;
    const startMs = toFiniteNumber(data.startMs ?? nested?.startMs);
    const durationMs = toFiniteNumber(data.durationMs ?? nested?.durationMs);
    if (startMs !== null && durationMs !== null) return startMs + durationMs;
    return null;
  }

  function parseTimestampToMs(value) {
    if (typeof value !== "string") return NaN;
    const trimmed = value.trim();
    if (!trimmed) return NaN;
    const parts = trimmed.split(":");
    if (parts.length < 2 || parts.length > 3) return NaN;
    const numbers = parts.map((part) => Number.parseInt(part, 10));
    if (numbers.some((n) => !Number.isFinite(n))) return NaN;
    if (numbers.length === 2) {
      const [m, s] = numbers;
      return (m * 60 + s) * 1000;
    }
    const [h, m, s] = numbers;
    return (h * 3600 + m * 60 + s) * 1000;
  }

  function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  function findTranscriptList() {
    return document.querySelector("ytd-transcript-segment-list-renderer");
  }

  async function openTranscriptPanel(maxWaitMs = 6_000) {
    if (findTranscriptList()) return true;

    // Expand description first — the "Show transcript" button lives there on modern YouTube.
    const expandBtn = document.querySelector(
      "ytd-text-inline-expander tp-yt-paper-button#expand, ytd-text-inline-expander #expand, #description #expand",
    );
    if (expandBtn) {
      expandBtn.click();
      await sleep(200);
    }

    // Find the transcript button. YouTube uses several variants over time; cover them all.
    const candidates = [
      'ytd-video-description-transcript-section-renderer button[aria-label*="ranscript" i]',
      'ytd-button-renderer button[aria-label*="ranscript" i]',
      'button[aria-label*="Show transcript" i]',
      'button[aria-label*="字幕" i]',
      'button[aria-label*="transcript" i]',
    ];
    let transcriptBtn = null;
    for (const selector of candidates) {
      transcriptBtn = document.querySelector(selector);
      if (transcriptBtn) break;
    }

    if (!transcriptBtn) return false;
    transcriptBtn.click();

    const started = performance.now();
    while (performance.now() - started < maxWaitMs) {
      const list = findTranscriptList();
      const rows = list?.querySelectorAll("ytd-transcript-segment-renderer");
      if (rows && rows.length > 0) return true;
      await sleep(200);
    }
    return false;
  }

  function readTranscriptFromDom() {
    const list = findTranscriptList();
    if (!list) return null;

    const rows = list.querySelectorAll("ytd-transcript-segment-renderer");
    if (rows.length === 0) return null;

    // Track which timing source was used so the popup can log it:
    // - "polymer-ms" = millisecond precision from YouTube's internal Polymer data (ideal)
    // - "data-attr"  = data-start-ms DOM attribute (ms precision)
    // - "text"       = parsed from "M:SS" displayed text (second precision, ±500ms drift)
    const precisionCounts = { "polymer-ms": 0, "data-attr": 0, text: 0 };

    const parsed = [];
    rows.forEach((row) => {
      let startMs = readStartMsFromRow(row);
      const endMs = readEndMsFromRow(row);
      let precision = "polymer-ms";

      if (startMs === null) {
        const segmentDiv = row.querySelector(".segment") ?? row;
        const attr =
          segmentDiv.getAttribute?.("data-start-ms") ?? row.getAttribute?.("data-start-ms") ?? null;
        if (attr != null) {
          const n = Number.parseInt(attr, 10);
          if (Number.isFinite(n)) {
            startMs = n;
            precision = "data-attr";
          }
        }
      }

      if (startMs === null) {
        const ts = row.querySelector(".segment-timestamp");
        const n = parseTimestampToMs(ts?.textContent ?? "");
        if (Number.isFinite(n)) {
          startMs = n;
          precision = "text";
        }
      }

      const textEl =
        row.querySelector(".segment-text yt-formatted-string") ??
        row.querySelector(".segment-text") ??
        row.querySelector("yt-formatted-string.segment-text");
      const text = normalizeText(textEl?.textContent ?? "");

      if (startMs !== null && text) {
        precisionCounts[precision] += 1;
        parsed.push({ startMs, endMs, text });
      }
    });

    if (parsed.length === 0) return null;

    // Fill missing endMs from the next segment's start; last segment gets +3s padding.
    const segments = parsed.map((seg, index) => {
      const next = parsed[index + 1];
      const resolvedEnd =
        seg.endMs !== null
          ? seg.endMs
          : next
            ? Math.max(next.startMs, seg.startMs + 200)
            : seg.startMs + 3_000;
      return { startMs: seg.startMs, endMs: resolvedEnd, text: seg.text };
    });

    return { segments, precisionCounts };
  }

  function parseXmlSegments(payloadText) {
    const xml = new DOMParser().parseFromString(payloadText, "text/xml");
    const textNodes = Array.from(xml.querySelectorAll("text"));

    return textNodes
      .map((node) => {
        const start = Number.parseFloat(node.getAttribute("start") ?? "");
        const duration = Number.parseFloat(node.getAttribute("dur") ?? "");
        const text = normalizeText(decodeHtml(node.textContent ?? ""));

        return {
          startMs: Math.round(start * 1_000),
          endMs: Math.round((start + Math.max(duration || 1.6, 0.2)) * 1_000),
          text,
        };
      })
      .filter(
        (segment) =>
          Number.isFinite(segment.startMs) && segment.endMs > segment.startMs && segment.text,
      );
  }

  function buildCandidateUrls(baseUrl, track) {
    const url = new URL(baseUrl);
    const seen = new Set();
    const candidates = [];

    function push(variant, transform) {
      const next = new URL(url);
      transform(next);
      const str = next.toString();
      if (seen.has(str)) return;
      seen.add(str);
      candidates.push({ variant, url: str });
    }

    // 1. Default (no fmt) — YouTube returns classic XML.
    push("xml-default", (u) => {
      u.searchParams.delete("fmt");
    });
    // 2. json3 — what YouTube's own player uses.
    push("json3", (u) => u.searchParams.set("fmt", "json3"));
    // 3. srv3 — legacy XML variant, sometimes bypasses newer silent-reject paths.
    push("srv3", (u) => u.searchParams.set("fmt", "srv3"));
    // 4. srv1 — oldest XML variant.
    push("srv1", (u) => u.searchParams.set("fmt", "srv1"));
    // 5. vtt — WebVTT format.
    push("vtt", (u) => u.searchParams.set("fmt", "vtt"));

    // For ASR tracks, make sure kind=asr is present on the URL (some endpoints
    // silent-reject ASR tracks if kind is missing).
    if (track?.kind === "asr") {
      push("json3+kind=asr", (u) => {
        u.searchParams.set("fmt", "json3");
        if (!u.searchParams.has("kind")) u.searchParams.set("kind", "asr");
      });
    }

    // 6. Original URL as-is.
    push("original", () => {});

    return candidates;
  }

  async function fetchTrackSegments(baseUrl, track) {
    const candidates = buildCandidateUrls(baseUrl, track);
    const attempts = [];

    for (const { variant, url: candidateUrl } of candidates) {
      const attempt = { variant, status: null, contentType: "", length: 0, preview: "" };
      attempts.push(attempt);

      let response;
      try {
        response = await fetch(candidateUrl, { credentials: "include" });
      } catch (error) {
        attempt.error = error instanceof Error ? error.message : String(error);
        continue;
      }
      attempt.status = response.status;
      attempt.contentType = response.headers.get("content-type") || "";

      if (!response.ok) continue;

      const payloadText = await response.text();
      attempt.length = payloadText.length;
      attempt.preview = payloadText.slice(0, 100).replace(/\s+/g, " ");

      if (!payloadText.trim()) continue;

      try {
        const jsonSegments = parseJson3Segments(payloadText);
        if (jsonSegments.length > 0) {
          attempt.parsed = `json3:${jsonSegments.length}`;
          return { segments: jsonSegments, attempts };
        }
      } catch {
        // Fall through to XML parsing.
      }

      const xmlSegments = parseXmlSegments(payloadText);
      if (xmlSegments.length > 0) {
        attempt.parsed = `xml:${xmlSegments.length}`;
        return { segments: xmlSegments, attempts };
      }

      attempt.parsed = "unrecognized";
    }

    // Summarize what we saw into a short human-readable error.
    const summary = attempts
      .map((a) => {
        if (a.error) return `${a.variant}=ERR(${a.error})`;
        return `${a.variant}=HTTP${a.status} ${a.length}b${a.parsed ? "/" + a.parsed : ""}`;
      })
      .join(", ");

    const err = new Error(
      `YouTube returned no usable captions across ${attempts.length} attempts. ${summary}`,
    );
    err.attempts = attempts;
    throw err;
  }

  function resolvePlayerAndVideoId() {
    const expectedVideoId = getVideoIdFromLocation();
    const playerResponse = readPlayerResponse();

    if (!playerResponse) {
      throw new Error(
        "Could not read YouTube player data. Try refreshing the page — SPA navigation sometimes leaves captions unreadable until a reload.",
      );
    }

    const videoDetails = playerResponse?.videoDetails;
    const playerVideoId = videoDetails?.videoId;
    const videoId = playerVideoId || expectedVideoId;
    if (!videoId) {
      throw new Error("Unable to determine the YouTube video ID.");
    }

    if (expectedVideoId && playerVideoId && expectedVideoId !== playerVideoId) {
      throw new Error(
        `Player data is still showing the previous video (${playerVideoId}) instead of ${expectedVideoId}. Please refresh the YouTube tab and try again.`,
      );
    }

    return { playerResponse, videoId };
  }

  async function extractPayload(trackIndex) {
    const { playerResponse, videoId } = resolvePlayerAndVideoId();
    const videoDetails = playerResponse?.videoDetails;
    const captionTracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

    if (!Array.isArray(captionTracks) || captionTracks.length === 0) {
      throw new Error("No caption tracks were found for this video.");
    }

    const effectiveIndex =
      Number.isInteger(trackIndex) && trackIndex >= 0 && trackIndex < captionTracks.length
        ? trackIndex
        : 0;
    const track = captionTracks[effectiveIndex];

    if (!track?.baseUrl || !track.languageCode) {
      throw new Error("The selected caption track is missing required metadata.");
    }

    let segments = null;
    let attempts = [];
    let source = "fetch";
    let fetchError = null;
    let precisionCounts = null;

    // Prefer the DOM path when the transcript panel is already open. It's both
    // faster (no ~500ms per fetch attempt) and immune to YouTube's silent-reject.
    if (findTranscriptList()) {
      await sleep(200);
      const domResult = readTranscriptFromDom();
      if (domResult && domResult.segments.length > 0) {
        segments = domResult.segments;
        precisionCounts = domResult.precisionCounts;
        source = "dom-prefetch";
      }
    }

    if (!segments || segments.length === 0) {
      try {
        const result = await fetchTrackSegments(track.baseUrl, track);
        segments = result.segments;
        attempts = result.attempts;
      } catch (error) {
        fetchError = error;
        attempts = error?.attempts ?? [];
      }
    }

    // Fallback path: YouTube's PO-token protection on timedtext returns HTTP 200
    // with empty text/html bodies. Reading the already-rendered transcript panel
    // sidesteps that entirely (no unsigned network request needed).
    if (!segments || segments.length === 0) {
      source = "dom";
      let panelOpened = Boolean(findTranscriptList());
      if (!panelOpened) {
        panelOpened = await openTranscriptPanel();
      }

      if (!panelOpened) {
        const err = new Error(
          (fetchError?.message ??
            "YouTube returned no usable caption data via the timedtext endpoint.") +
            " Additionally, I could not open the on-page Transcript panel automatically. " +
            'On YouTube, click "…more" under the video → "Show transcript", then retry.',
        );
        err.attempts = attempts;
        throw err;
      }

      // Small settle so the last few rows get rendered before we read.
      await sleep(300);
      const domResult = readTranscriptFromDom();
      if (!domResult || !domResult.segments || domResult.segments.length === 0) {
        const err = new Error(
          "Transcript panel is open but contains no readable segments. It may still be loading — wait a moment and retry.",
        );
        err.attempts = attempts;
        throw err;
      }
      segments = domResult.segments;
      precisionCounts = domResult.precisionCounts;
    }

    return {
      payload: {
        version: 1,
        source: "shadowing-space-extension",
        exportedAt: new Date().toISOString(),
        video: {
          videoId,
          title: videoDetails?.title || document.title.replace(/\s*-\s*YouTube$/, ""),
          thumbnailUrl: getThumbnailUrl(videoDetails),
        },
        track: {
          languageCode: track.languageCode,
          label: labelFromName(track.name, track.languageCode),
          isAutoGenerated: track.kind === "asr",
          originTrackId: track.vssId || track.languageCode,
        },
        segments,
      },
      debug: {
        attempts,
        source,
        precisionCounts,
        fetchError: fetchError?.message ?? null,
      },
    };
  }

  function post(type, ok, extras) {
    window.postMessage({ type, ok, ...extras }, window.location.origin);
  }

  window.addEventListener(LIST_REQUEST_EVENT, () => {
    try {
      const { playerResponse } = resolvePlayerAndVideoId();
      const summary = buildSummary(playerResponse);
      post(LIST_RESULT_TYPE, true, { summary });
    } catch (error) {
      post(LIST_RESULT_TYPE, false, {
        error: error instanceof Error ? error.message : String(error),
      });
    }
  });

  window.addEventListener(EXTRACT_REQUEST_EVENT, (event) => {
    const trackIndex =
      typeof event?.detail?.trackIndex === "number" ? event.detail.trackIndex : undefined;

    void (async () => {
      try {
        const result = await extractPayload(trackIndex);
        post(EXTRACT_RESULT_TYPE, true, {
          payload: result.payload,
          debug: result.debug,
        });
      } catch (error) {
        const debug =
          error && typeof error === "object" && "attempts" in error
            ? { attempts: /** @type {any} */ (error).attempts }
            : undefined;
        post(EXTRACT_RESULT_TYPE, false, {
          error: error instanceof Error ? error.message : String(error),
          debug,
        });
      }
    })();
  });
})();
