export type TrackSummary = {
  token: string;
  languageCode: string;
  label: string;
  isAutoGenerated: boolean;
};

export type SegmentDTO = {
  index: number;
  startMs: number;
  endMs: number;
  text: string;
};

export type FetchTranscriptRequest = {
  url: string;
  preferredLanguage?: string;
  useProxy?: boolean;
};

export type FetchTranscriptResponse = {
  videoId: string;
  title: string;
  durationSec?: number;
  thumbnailUrl?: string;
  tracks: TrackSummary[];
  defaultTrackToken: string;
};

export type ResolveTranscriptRequest = {
  videoId: string;
  trackToken: string;
  useProxy?: boolean;
};

export type ResolveTranscriptResponse = {
  videoId: string;
  track: TrackSummary;
  segments: SegmentDTO[];
};
