export type VideoRecord = {
  id: string;
  youtubeVideoId: string;
  title: string;
  thumbnailUrl?: string;
  createdAt: number;
};

export type TrackRecord = {
  id: string;
  videoId: string;
  token: string;
  languageCode: string;
  label: string;
  isAutoGenerated: boolean;
  createdAt: number;
};

export type SegmentRecord = {
  id: string;
  trackId: string;
  index: number;
  startMs: number;
  endMs: number;
  text: string;
};

export type ProgressRecord = {
  trackId: string;
  currentIndex: number;
  updatedAt: number;
};

export type RecordingRecord = {
  id: string;
  trackId: string;
  segmentIndex: number;
  blob: Blob;
  mimeType: string;
  durationMs: number;
  updatedAt: number;
};

export type HistoryItem = {
  video: VideoRecord;
  activeTrack?: TrackRecord;
  progress?: ProgressRecord;
  segmentCount: number;
  recordingCount: number;
  recordingSizeBytes: number;
};
