import assert from "node:assert/strict";
import test from "node:test";
import { createTrackToken } from "@/server/youtube/trackToken";
import { fetchTranscriptMetadata, resolveTranscriptSegments } from "@/server/youtube/service";

const originalFetch = global.fetch;

test("fetchTranscriptMetadata returns tracks from innertube player", async () => {
  const innertubeResponse = {
    videoDetails: {
      title: "Demo",
      lengthSeconds: "120",
      thumbnail: { thumbnails: [{ url: "thumb-small" }, { url: "thumb-large" }] }
    },
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [
          {
            baseUrl: "https://www.youtube.com/api/timedtext?v=FRI78tq9Eik&lang=en",
            languageCode: "en",
            name: { simpleText: "English" }
          }
        ]
      }
    }
  };

  global.fetch = async () =>
    new Response(JSON.stringify(innertubeResponse), {
      status: 200,
      headers: { "Content-Type": "application/json" }
    });

  const result = await fetchTranscriptMetadata({
    url: "https://www.youtube.com/watch?v=FRI78tq9Eik",
    preferredLanguage: "en",
    timeoutMs: 5000,
    trackTokenSecret: "secret",
    trackTokenTtlSeconds: 3600
  });

  assert.equal(result.videoId, "FRI78tq9Eik");
  assert.equal(result.title, "Demo");
  assert.equal(result.durationSec, 120);
  assert.equal(result.thumbnailUrl, "thumb-large");
  assert.equal(result.tracks.length, 1);

  global.fetch = originalFetch;
});

test("resolveTranscriptSegments parses json3 payload", async () => {
  const token = createTrackToken(
    {
      videoId: "FRI78tq9Eik",
      baseUrl: "https://www.youtube.com/api/timedtext?v=FRI78tq9Eik&lang=en",
      languageCode: "en",
      label: "English",
      isAutoGenerated: false
    },
    "secret",
    3600
  );

  const payload = JSON.stringify({
    events: [{ tStartMs: 0, dDurationMs: 1500, segs: [{ utf8: "Hello" }] }]
  });

  global.fetch = async () => new Response(payload, { status: 200 });

  const result = await resolveTranscriptSegments({
    videoId: "FRI78tq9Eik",
    trackToken: token,
    timeoutMs: 5000,
    trackTokenSecret: "secret"
  });

  assert.equal(result.segments.length, 1);
  assert.equal(result.track.languageCode, "en");

  global.fetch = originalFetch;
});

test("resolveTranscriptSegments tries exact caption URL before derived variants", async () => {
  const baseUrl = "https://www.youtube.com/api/timedtext?v=FRI78tq9Eik&sig=A%2BB%2F%3D";
  const token = createTrackToken(
    {
      videoId: "FRI78tq9Eik",
      baseUrl,
      languageCode: "en",
      label: "English",
      isAutoGenerated: false
    },
    "secret",
    3600
  );

  const calls: string[] = [];
  const payload = JSON.stringify({
    events: [{ tStartMs: 0, dDurationMs: 1200, segs: [{ utf8: "Hello" }] }]
  });

  global.fetch = async (input) => {
    const url = String(input);
    calls.push(url);

    if (url === baseUrl) {
      return new Response(payload, { status: 200 });
    }

    return new Response("", { status: 200 });
  };

  const result = await resolveTranscriptSegments({
    videoId: "FRI78tq9Eik",
    trackToken: token,
    timeoutMs: 5000,
    trackTokenSecret: "secret"
  });

  assert.equal(calls[0], baseUrl);
  assert.equal(result.segments.length, 1);

  global.fetch = originalFetch;
});

test("resolveTranscriptSegments falls back to vtt when other formats are empty", async () => {
  const baseUrl = "https://www.youtube.com/api/timedtext?v=FRI78tq9Eik&lang=en";
  const token = createTrackToken(
    {
      videoId: "FRI78tq9Eik",
      baseUrl,
      languageCode: "en",
      label: "English",
      isAutoGenerated: false
    },
    "secret",
    3600
  );

  const calls: string[] = [];
  const vttPayload = `WEBVTT\n\n00:00:00.000 --> 00:00:01.200\nFallback works\n`;

  global.fetch = async (input) => {
    const url = String(input);
    calls.push(url);

    if (url.includes("fmt=vtt")) {
      return new Response(vttPayload, { status: 200 });
    }

    return new Response("", { status: 200 });
  };

  const result = await resolveTranscriptSegments({
    videoId: "FRI78tq9Eik",
    trackToken: token,
    timeoutMs: 5000,
    trackTokenSecret: "secret"
  });

  assert.ok(calls.some((url) => url.includes("fmt=vtt")));
  assert.equal(result.segments.length, 1);
  assert.equal(result.segments[0]?.text, "Fallback works");

  global.fetch = originalFetch;
});
