import assert from "node:assert/strict";
import test from "node:test";
import { createTrackToken, parseTrackToken } from "@/server/youtube/trackToken";

test("track token signs and validates payload", () => {
  const token = createTrackToken(
    {
      videoId: "FRI78tq9Eik",
      baseUrl: "https://www.youtube.com/api/timedtext?v=FRI78tq9Eik",
      languageCode: "en",
      label: "English",
      isAutoGenerated: false,
    },
    "secret",
    3600,
  );

  const payload = parseTrackToken(token, "secret");
  assert.equal(payload.videoId, "FRI78tq9Eik");
  assert.equal(payload.languageCode, "en");
});

test("track token rejects tampered signatures", () => {
  const token = createTrackToken(
    {
      videoId: "FRI78tq9Eik",
      baseUrl: "https://www.youtube.com/api/timedtext?v=FRI78tq9Eik",
      languageCode: "en",
      label: "English",
      isAutoGenerated: false,
    },
    "secret",
    3600,
  );

  assert.throws(() => parseTrackToken(`${token}x`, "secret"));
});

test("track token preserves caption URL query bytes", () => {
  const baseUrl =
    "https://www.youtube.com/api/timedtext?v=FRI78tq9Eik&sig=A%2BB%2F%3D&x=1&x=2&fmt=srv3";

  const token = createTrackToken(
    {
      videoId: "FRI78tq9Eik",
      baseUrl,
      languageCode: "en",
      label: "English",
      isAutoGenerated: false,
    },
    "secret",
    3600,
  );

  const payload = parseTrackToken(token, "secret");
  assert.equal(payload.baseUrl, baseUrl);
});
