import assert from "node:assert/strict";
import test from "node:test";
import {
  createEnvelope,
  HANDOFF_STORAGE_KEY,
  HANDOFF_TTL_MS,
  isEnvelopeFresh,
} from "../../extension/lib/handoff.js";

const fakePayload = {
  version: 1 as const,
  source: "shadowing-space-extension" as const,
  exportedAt: "2026-04-16T08:00:00.000Z",
  video: { videoId: "abc", title: "t" },
  track: { languageCode: "en", label: "English", isAutoGenerated: false },
  segments: [{ startMs: 0, endMs: 1000, text: "Hi." }],
};

test("createEnvelope wraps the payload with timestamp + version", () => {
  const envelope = createEnvelope(fakePayload, 12_345);
  assert.equal(envelope.version, 1);
  assert.equal(envelope.createdAt, 12_345);
  assert.equal(envelope.payload, fakePayload);
});

test("HANDOFF_STORAGE_KEY is a stable string constant", () => {
  assert.equal(typeof HANDOFF_STORAGE_KEY, "string");
  assert.ok(HANDOFF_STORAGE_KEY.length > 0);
});

test("isEnvelopeFresh returns true within TTL", () => {
  const envelope = createEnvelope(fakePayload, 1_000_000);
  assert.equal(isEnvelopeFresh(envelope, 1_000_500), true);
  assert.equal(isEnvelopeFresh(envelope, 1_000_000 + HANDOFF_TTL_MS - 1), true);
});

test("isEnvelopeFresh returns false after TTL elapses", () => {
  const envelope = createEnvelope(fakePayload, 1_000_000);
  assert.equal(isEnvelopeFresh(envelope, 1_000_000 + HANDOFF_TTL_MS + 1), false);
  assert.equal(isEnvelopeFresh(envelope, 9_999_999_999), false);
});

test("isEnvelopeFresh rejects malformed envelopes", () => {
  assert.equal(isEnvelopeFresh(null, 0), false);
  assert.equal(isEnvelopeFresh(undefined, 0), false);
  assert.equal(isEnvelopeFresh({}, 0), false);
  assert.equal(isEnvelopeFresh({ version: 2, createdAt: 0, payload: fakePayload }, 0), false);
  assert.equal(isEnvelopeFresh({ version: 1, createdAt: "x", payload: fakePayload }, 0), false);
  assert.equal(isEnvelopeFresh({ version: 1, createdAt: 0 }, 0), false);
});
