import assert from "node:assert/strict";
import test from "node:test";
import {
  buildDownloadFilename,
  summarizeTracks,
  type CaptionTrackLike,
} from "../../extension/lib/player-response.js";

function track(overrides: Partial<CaptionTrackLike> = {}): CaptionTrackLike {
  return {
    baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en",
    languageCode: "en",
    name: { simpleText: "English" },
    ...overrides,
  };
}

test("summarizeTracks returns title, video id and normalized track entries", () => {
  const response = {
    videoDetails: {
      videoId: "FRI78tq9Eik",
      title: "Daily Speaking Drill",
      thumbnail: { thumbnails: [{ url: "https://i.ytimg.com/vi/x/hqdefault.jpg" }] },
    },
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [
          track({ languageCode: "en", name: { simpleText: "English" } }),
          track({
            languageCode: "en",
            kind: "asr",
            name: { simpleText: "English (auto)" },
            vssId: "a.en",
          }),
          track({
            languageCode: "ja",
            name: { runs: [{ text: "日本語" }] },
            vssId: ".ja",
          }),
        ],
      },
    },
  };

  const summary = summarizeTracks(response);

  assert.equal(summary.video.videoId, "FRI78tq9Eik");
  assert.equal(summary.video.title, "Daily Speaking Drill");
  assert.equal(summary.video.thumbnailUrl, "https://i.ytimg.com/vi/x/hqdefault.jpg");

  assert.equal(summary.tracks.length, 3);
  assert.equal(summary.tracks[0].languageCode, "en");
  assert.equal(summary.tracks[0].label, "English");
  assert.equal(summary.tracks[0].isAutoGenerated, false);
  assert.equal(summary.tracks[0].trackIndex, 0);

  assert.equal(summary.tracks[1].languageCode, "en");
  assert.equal(summary.tracks[1].isAutoGenerated, true);
  assert.equal(summary.tracks[1].trackIndex, 1);

  assert.equal(summary.tracks[2].languageCode, "ja");
  assert.equal(summary.tracks[2].label, "日本語");
  assert.equal(summary.tracks[2].trackIndex, 2);
});

test("summarizeTracks returns empty tracks when captions are missing", () => {
  const summary = summarizeTracks({ videoDetails: { videoId: "x", title: "T" } });
  assert.equal(summary.video.videoId, "x");
  assert.deepEqual(summary.tracks, []);
});

test("summarizeTracks returns empty summary for non-player-response input", () => {
  const summary = summarizeTracks(null);
  assert.equal(summary.video.videoId, "");
  assert.equal(summary.video.title, "");
  assert.deepEqual(summary.tracks, []);
});

test("buildDownloadFilename composes a slug from video id + language + auto flag", () => {
  assert.equal(
    buildDownloadFilename({ videoId: "FRI78tq9Eik", languageCode: "en", isAutoGenerated: false }),
    "shadowing-FRI78tq9Eik-en.json",
  );
  assert.equal(
    buildDownloadFilename({ videoId: "FRI78tq9Eik", languageCode: "en", isAutoGenerated: true }),
    "shadowing-FRI78tq9Eik-en-auto.json",
  );
});

test("buildDownloadFilename sanitizes unsafe characters from language code", () => {
  assert.equal(
    buildDownloadFilename({
      videoId: "abc123",
      languageCode: "zh-Hans",
      isAutoGenerated: false,
    }),
    "shadowing-abc123-zh-Hans.json",
  );

  assert.equal(
    buildDownloadFilename({
      videoId: "../secret",
      languageCode: "en\\x",
      isAutoGenerated: false,
    }),
    "shadowing-secret-enx.json",
  );
});

test("buildDownloadFilename falls back to 'unknown' for empty inputs", () => {
  assert.equal(
    buildDownloadFilename({ videoId: "", languageCode: "", isAutoGenerated: false }),
    "shadowing-unknown-unknown.json",
  );
});
