"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { clearAllData, listHistory } from "@/features/storage/repository";
import type { HistoryItem } from "@/types/models";

function formatTime(timestamp: number): string {
  return new Date(timestamp).toLocaleString();
}

export function HistoryClient(): JSX.Element {
  const router = useRouter();
  const [items, setItems] = useState<HistoryItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [status, setStatus] = useState<string | undefined>();
  const [error, setError] = useState<string | undefined>();

  const refresh = async () => {
    setError(undefined);
    setIsLoading(true);

    try {
      const next = await listHistory();
      setItems(next);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : "Failed to load history.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    void refresh();
  }, []);

  const handleReset = async () => {
    setError(undefined);
    setStatus(undefined);

    try {
      await clearAllData();
      setStatus("All local data is cleared.");
      await refresh();
    } catch (clearError) {
      setError(clearError instanceof Error ? clearError.message : "Failed to clear local data.");
    }
  };

  return (
    <section className="card">
      <h2>History</h2>
      <p className="muted">Resume past practice sessions from local IndexedDB storage.</p>

      <div className="actions-row">
        <Link href="/" className="btn primary inline-btn">
          Import New Video
        </Link>
        <button className="btn secondary" type="button" onClick={handleReset}>
          Reset Local Data
        </button>
      </div>

      {status ? <p className="success-text">{status}</p> : null}
      {error ? <p className="error-text">{error}</p> : null}
      {isLoading ? <p className="muted">Loading history...</p> : null}
      {!isLoading && items.length === 0 ? <p className="muted">No practice history yet.</p> : null}

      <div className="history-list">
        {items.map((item) => (
          <article key={item.video.id} className="history-item">
            <div>
              <h3>{item.video.title}</h3>
              <p className="muted">Video ID: {item.video.youtubeVideoId}</p>
              <p className="muted">Imported at: {formatTime(item.video.createdAt)}</p>
              {item.activeTrack ? (
                <p className="muted">
                  Track: {item.activeTrack.label}
                  {item.activeTrack.isAutoGenerated ? " (auto)" : ""}
                </p>
              ) : (
                <p className="muted">No track selected yet.</p>
              )}
              {item.progress ? (
                <p className="muted">Last sentence: #{item.progress.currentIndex + 1}</p>
              ) : (
                <p className="muted">No saved progress yet.</p>
              )}
              <p className="muted">Sentence count: {item.segmentCount}</p>
            </div>

            <div className="actions-row">
              <button
                className="btn primary"
                type="button"
                disabled={!item.activeTrack}
                onClick={() => {
                  if (!item.activeTrack) {
                    return;
                  }

                  router.push(`/practice/${item.video.id}/${encodeURIComponent(item.activeTrack.id)}`);
                }}
              >
                Continue
              </button>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
