"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { clearAllData, deleteVideo, listHistory } from "@/features/storage/repository";
import type { HistoryItem } from "@/types/models";

function formatTime(timestamp: number): string {
  return new Date(timestamp).toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric"
  });
}

export function HistoryClient(): JSX.Element {
  const router = useRouter();
  const [items, setItems] = useState<HistoryItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | undefined>();

  const refresh = async () => {
    setError(undefined);
    setIsLoading(true);

    try {
      const next = await listHistory();
      setItems(next);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : "Failed to load history.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    void refresh();
  }, []);

  const handleDelete = async (videoId: string, title: string) => {
    if (!window.confirm(`Delete "${title}" and all its practice data?`)) {
      return;
    }

    try {
      await deleteVideo(videoId);
      await refresh();
    } catch (deleteError) {
      setError(deleteError instanceof Error ? deleteError.message : "Failed to delete video.");
    }
  };

  const handleReset = async () => {
    if (!window.confirm("Delete ALL local data? This cannot be undone.")) {
      return;
    }

    try {
      await clearAllData();
      await refresh();
    } catch (clearError) {
      setError(clearError instanceof Error ? clearError.message : "Failed to clear local data.");
    }
  };

  return (
    <section>
      <div className="dashboard-header">
        <div>
          <h2>Dashboard</h2>
          <p className="muted">Your studied videos and practice progress.</p>
        </div>
        <Link href="/" className="btn primary inline-btn">
          + Import New Video
        </Link>
      </div>

      {error ? <p className="error-text">{error}</p> : null}
      {isLoading ? <p className="muted">Loading...</p> : null}

      {!isLoading && items.length === 0 ? (
        <div className="card empty-state">
          <p>No videos yet.</p>
          <Link href="/" className="btn primary inline-btn">
            Import your first video
          </Link>
        </div>
      ) : null}

      <div className="dashboard-grid">
        {items.map((item) => {
          const progress = item.progress;
          const progressPct =
            item.segmentCount > 0 && progress
              ? Math.round(((progress.currentIndex + 1) / item.segmentCount) * 100)
              : 0;

          return (
            <article key={item.video.id} className="video-card">
              {item.video.thumbnailUrl ? (
                <img
                  className="video-card-thumb"
                  src={item.video.thumbnailUrl}
                  alt=""
                  loading="lazy"
                />
              ) : (
                <div className="video-card-thumb video-card-thumb-placeholder" />
              )}

              <div className="video-card-body">
                <h3 className="video-card-title">{item.video.title}</h3>

                <p className="muted video-card-meta">
                  {item.activeTrack?.label ?? "No track"}
                  {item.activeTrack?.isAutoGenerated ? " (auto)" : ""}
                  {" · "}
                  {formatTime(item.video.createdAt)}
                </p>

                {item.segmentCount > 0 ? (
                  <div className="progress-bar">
                    <div className="progress-fill" style={{ width: `${progressPct}%` }} />
                  </div>
                ) : null}

                <p className="muted video-card-stats">
                  {progress
                    ? `Sentence ${progress.currentIndex + 1} / ${item.segmentCount}`
                    : `${item.segmentCount} sentences`}
                  {item.recordingCount > 0 ? ` · ${item.recordingCount} recorded` : ""}
                </p>
              </div>

              <div className="video-card-actions">
                <button
                  className="btn primary"
                  type="button"
                  disabled={!item.activeTrack}
                  onClick={() => {
                    if (!item.activeTrack) {
                      return;
                    }
                    router.push(
                      `/practice/${item.video.id}/${encodeURIComponent(item.activeTrack.id)}`
                    );
                  }}
                >
                  Continue
                </button>
                <button
                  className="btn secondary"
                  type="button"
                  onClick={() => void handleDelete(item.video.id, item.video.title)}
                >
                  Delete
                </button>
              </div>
            </article>
          );
        })}
      </div>

      {items.length > 0 ? (
        <p className="reset-link">
          <button type="button" className="text-btn muted" onClick={() => void handleReset()}>
            Reset all local data
          </button>
        </p>
      ) : null}
    </section>
  );
}
