export function buildTrackId(videoId: string, token: string): string {
  return `${videoId}:${token}`;
}

export function buildSegmentId(trackId: string, index: number): string {
  return `${trackId}:${index}`;
}

export function buildRecordingId(trackId: string, segmentIndex: number): string {
  return `${trackId}:${segmentIndex}`;
}

export function buildVocabularyId(trackId: string, normalizedWord: string): string {
  return `${trackId}:vocab:${normalizedWord}`;
}

export function buildStudySessionId(trackId: string, endedAt: number): string {
  const suffix = globalThis.crypto?.randomUUID?.() ?? Math.random().toString(36).slice(2, 10);
  return `${trackId}:study:${endedAt}:${suffix}`;
}

export function buildLocalDayKey(timestamp: number): string {
  const date = new Date(timestamp);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export function buildIdCandidates(value: string): string[] {
  const candidates = [value];
  let decoded = value;

  // Try decoding twice so both encoded and double-encoded IDs can resolve.
  for (let index = 0; index < 2; index += 1) {
    try {
      const next = decodeURIComponent(decoded);
      if (next === decoded) {
        break;
      }
      decoded = next;
      if (!candidates.includes(decoded)) {
        candidates.push(decoded);
      }
    } catch {
      break;
    }
  }

  return candidates;
}

export function trackMatchKey(languageCode: string, isAutoGenerated: boolean): string {
  return `${languageCode.toLowerCase()}:${isAutoGenerated}`;
}
