import Dexie from "dexie";
import { db } from "@/features/storage/db";
import { cleanVocabularyText, normalizeVocabularyKey } from "@/features/vocabulary/words";
import type { SegmentDTO, TrackSummary } from "@/types/api";
import type {
  FreeRecordingRecord,
  HistoryItem,
  ProgressRecord,
  RecordingRecord,
  SegmentRecord,
  TrackRecord,
  VocabularyRecord,
  VideoRecord,
} from "@/types/models";

export function buildTrackId(videoId: string, token: string): string {
  return `${videoId}:${token}`;
}

function buildSegmentId(trackId: string, index: number): string {
  return `${trackId}:${index}`;
}

function buildRecordingId(trackId: string, segmentIndex: number): string {
  return `${trackId}:${segmentIndex}`;
}

function buildVocabularyId(trackId: string, normalizedWord: string): string {
  return `${trackId}:vocab:${normalizedWord}`;
}

function buildIdCandidates(value: string): string[] {
  const candidates = [value];
  let decoded = value;

  // Try decoding twice so both encoded and double-encoded IDs can resolve.
  for (let index = 0; index < 2; index += 1) {
    try {
      const next = decodeURIComponent(decoded);
      if (next === decoded) {
        break;
      }
      decoded = next;
      if (!candidates.includes(decoded)) {
        candidates.push(decoded);
      }
    } catch {
      break;
    }
  }

  return candidates;
}

export function mapTracks(
  videoId: string,
  tracks: TrackSummary[],
  createdAt: number,
): TrackRecord[] {
  return tracks.map((track) => ({
    id: buildTrackId(videoId, track.token),
    videoId,
    token: track.token,
    languageCode: track.languageCode,
    label: track.label,
    isAutoGenerated: track.isAutoGenerated,
    createdAt,
  }));
}

export function mapSegments(trackId: string, segments: SegmentDTO[]): SegmentRecord[] {
  return segments.map((segment) => ({
    id: buildSegmentId(trackId, segment.index),
    trackId,
    index: segment.index,
    startMs: segment.startMs,
    endMs: segment.endMs,
    text: segment.text,
  }));
}

function trackMatchKey(languageCode: string, isAutoGenerated: boolean): string {
  return `${languageCode.toLowerCase()}:${isAutoGenerated}`;
}

export async function saveImportBundle(params: {
  video: VideoRecord;
  tracks: TrackRecord[];
  targetTrackId: string;
  segments: SegmentRecord[];
}): Promise<{ effectiveTargetTrackId: string }> {
  const { video, tracks, targetTrackId, segments } = params;
  let effectiveTargetId = targetTrackId;

  await db.transaction(
    "rw",
    [
      db.videos,
      db.tracks,
      db.segments,
      db.progress,
      db.recordings,
      db.freeRecordings,
      db.vocabulary,
    ],
    async () => {
      await db.videos.put(video);

      const existingTracks = await db.tracks.where("videoId").equals(video.id).toArray();
      const existingByKey = new Map<string, TrackRecord>();
      for (const t of existingTracks) {
        existingByKey.set(trackMatchKey(t.languageCode, t.isAutoGenerated), t);
      }

      // Map new track IDs to old ones when a (languageCode, isAutoGenerated) match exists
      const idRemap = new Map<string, string>(); // newId -> oldId
      const matchedOldIds = new Set<string>();

      for (const newTrack of tracks) {
        const key = trackMatchKey(newTrack.languageCode, newTrack.isAutoGenerated);
        const existing = existingByKey.get(key);
        if (existing) {
          idRemap.set(newTrack.id, existing.id);
          matchedOldIds.add(existing.id);
        }
      }

      // Clean up orphaned tracks (exist in old set but no match in new set)
      for (const oldTrack of existingTracks) {
        if (!matchedOldIds.has(oldTrack.id)) {
          await db.segments.where("trackId").equals(oldTrack.id).delete();
          await db.recordings.where("trackId").equals(oldTrack.id).delete();
          await db.freeRecordings.where("trackId").equals(oldTrack.id).delete();
          await db.vocabulary.where("trackId").equals(oldTrack.id).delete();
          await db.progress.delete(oldTrack.id);
        }
      }

      // Delete old tracks, insert new ones with remapped IDs
      await db.tracks.where("videoId").equals(video.id).delete();
      const remappedTracks = tracks.map((t) => ({
        ...t,
        id: idRemap.get(t.id) ?? t.id,
      }));
      await db.tracks.bulkPut(remappedTracks);

      // Resolve the effective target track ID
      effectiveTargetId = idRemap.get(targetTrackId) ?? targetTrackId;

      // Replace segments for the target track only
      await db.segments.where("trackId").equals(effectiveTargetId).delete();
      if (segments.length > 0) {
        const remappedSegments = segments.map((s) => ({
          ...s,
          id: buildSegmentId(effectiveTargetId, s.index),
          trackId: effectiveTargetId,
        }));
        await db.segments.bulkPut(remappedSegments);
      }

      // Initialize progress only if none exists for this track
      const existingProgress = await db.progress.get(effectiveTargetId);
      if (!existingProgress) {
        await db.progress.put({
          trackId: effectiveTargetId,
          currentIndex: 0,
          updatedAt: Date.now(),
        });
      }
    },
  );

  return { effectiveTargetTrackId: effectiveTargetId };
}

export async function saveSegmentsForTrack(
  trackId: string,
  segments: SegmentRecord[],
): Promise<void> {
  await db.transaction("rw", db.segments, async () => {
    await db.segments.where("trackId").equals(trackId).delete();
    if (segments.length > 0) {
      await db.segments.bulkPut(segments);
    }
  });
}

export async function getPracticeSession(
  videoId: string,
  trackId: string,
): Promise<{
  video?: VideoRecord;
  track?: TrackRecord;
  tracks: TrackRecord[];
  segments: SegmentRecord[];
  progress?: ProgressRecord;
}> {
  const videoIdCandidates = buildIdCandidates(videoId);
  const trackIdCandidates = buildIdCandidates(trackId);

  const [videoCandidates, trackCandidates, tracks, progressCandidates] = await Promise.all([
    Promise.all(videoIdCandidates.map((candidate) => db.videos.get(candidate))),
    Promise.all(trackIdCandidates.map((candidate) => db.tracks.get(candidate))),
    db.tracks.where("videoId").anyOf(videoIdCandidates).toArray(),
    Promise.all(trackIdCandidates.map((candidate) => db.progress.get(candidate))),
  ]);

  const video = videoCandidates.find((candidate): candidate is VideoRecord => Boolean(candidate));
  const track =
    trackCandidates.find((candidate): candidate is TrackRecord => Boolean(candidate)) ??
    tracks.find((candidate) => trackIdCandidates.includes(candidate.id));
  const resolvedTrackId = track?.id ?? trackIdCandidates[0];
  const progress = progressCandidates.find((candidate): candidate is ProgressRecord =>
    Boolean(candidate),
  );

  const segments = await db.segments
    .where("[trackId+index]")
    .between([resolvedTrackId, Dexie.minKey], [resolvedTrackId, Dexie.maxKey])
    .sortBy("index");

  return {
    video,
    track,
    tracks,
    segments,
    progress,
  };
}

export async function deleteVideo(videoId: string): Promise<void> {
  await db.transaction(
    "rw",
    [
      db.videos,
      db.tracks,
      db.segments,
      db.progress,
      db.recordings,
      db.freeRecordings,
      db.vocabulary,
    ],
    async () => {
      const tracks = await db.tracks.where("videoId").equals(videoId).toArray();
      for (const track of tracks) {
        await db.segments.where("trackId").equals(track.id).delete();
        await db.recordings.where("trackId").equals(track.id).delete();
        await db.freeRecordings.where("trackId").equals(track.id).delete();
        await db.vocabulary.where("trackId").equals(track.id).delete();
        await db.progress.delete(track.id);
      }
      await db.tracks.where("videoId").equals(videoId).delete();
      await db.videos.delete(videoId);
    },
  );
}

export async function deleteRecordingsForVideo(videoId: string): Promise<void> {
  await db.transaction("rw", [db.tracks, db.recordings, db.freeRecordings], async () => {
    const tracks = await db.tracks.where("videoId").equals(videoId).toArray();
    for (const track of tracks) {
      await db.recordings.where("trackId").equals(track.id).delete();
      await db.freeRecordings.where("trackId").equals(track.id).delete();
    }
  });
}

export async function getRecordedSegmentIndices(trackId: string): Promise<Set<number>> {
  const recordings = await db.recordings.where("trackId").equals(trackId).toArray();
  return new Set(recordings.map((r) => r.segmentIndex));
}

export async function listHistory(): Promise<HistoryItem[]> {
  // Phase 1: load lightweight metadata only (no segment text or recording blobs)
  const [videos, tracks, progressItems] = await Promise.all([
    db.videos.toArray(),
    db.tracks.toArray(),
    db.progress.toArray(),
  ]);

  const tracksByVideo = new Map<string, TrackRecord[]>();
  for (const track of tracks) {
    const list = tracksByVideo.get(track.videoId) ?? [];
    list.push(track);
    tracksByVideo.set(track.videoId, list);
  }

  const progressByTrack = new Map<string, ProgressRecord>();
  for (const item of progressItems) {
    progressByTrack.set(item.trackId, item);
  }

  // Determine the active track per video before querying segments/recordings
  const videoEntries: Array<{
    video: VideoRecord;
    activeTrack?: TrackRecord;
    activeProgress?: ProgressRecord;
  }> = [];

  const activeTrackIds: string[] = [];

  for (const video of videos) {
    const videoTracks = tracksByVideo.get(video.id) ?? [];
    let activeTrack: TrackRecord | undefined;
    let activeProgress: ProgressRecord | undefined;

    for (const track of videoTracks) {
      const progress = progressByTrack.get(track.id);
      if (!progress) continue;
      if (!activeProgress || progress.updatedAt > activeProgress.updatedAt) {
        activeProgress = progress;
        activeTrack = track;
      }
    }

    if (!activeTrack && videoTracks.length > 0) {
      activeTrack = videoTracks[0];
    }

    videoEntries.push({ video, activeTrack, activeProgress });
    if (activeTrack) {
      activeTrackIds.push(activeTrack.id);
    }
  }

  // Phase 2: count segments (index-only, no text loaded) and load recordings
  // only for active tracks
  const [segmentCounts, recordingStats, freeRecordingStats] = await Promise.all([
    Promise.all(
      activeTrackIds.map(async (trackId) => {
        const count = await db.segments.where("trackId").equals(trackId).count();
        return [trackId, count] as const;
      }),
    ),
    Promise.all(
      activeTrackIds.map(async (trackId) => {
        const recordings = await db.recordings.where("trackId").equals(trackId).toArray();
        let totalSize = 0;
        for (const r of recordings) {
          totalSize += r.blob.size;
        }
        return [trackId, recordings.length, totalSize] as const;
      }),
    ),
    Promise.all(
      activeTrackIds.map(async (trackId) => {
        const freeRecs = await db.freeRecordings.where("trackId").equals(trackId).toArray();
        let totalSize = 0;
        for (const r of freeRecs) {
          totalSize += r.blob.size;
        }
        return [trackId, freeRecs.length, totalSize] as const;
      }),
    ),
  ]);

  const segmentCountByTrack = new Map(segmentCounts);
  const recordingCountByTrack = new Map<string, number>();
  const recordingSizeByTrack = new Map<string, number>();
  for (const [trackId, count, size] of recordingStats) {
    recordingCountByTrack.set(trackId, count);
    recordingSizeByTrack.set(trackId, size);
  }
  for (const [trackId, count, size] of freeRecordingStats) {
    recordingCountByTrack.set(trackId, (recordingCountByTrack.get(trackId) ?? 0) + count);
    recordingSizeByTrack.set(trackId, (recordingSizeByTrack.get(trackId) ?? 0) + size);
  }

  const items = videoEntries.map(({ video, activeTrack, activeProgress }) => {
    const segmentCount = activeTrack ? (segmentCountByTrack.get(activeTrack.id) ?? 0) : 0;
    const recordingCount = activeTrack ? (recordingCountByTrack.get(activeTrack.id) ?? 0) : 0;
    const recordingSizeBytes = activeTrack ? (recordingSizeByTrack.get(activeTrack.id) ?? 0) : 0;

    return {
      video,
      activeTrack,
      progress: activeProgress,
      segmentCount,
      recordingCount,
      recordingSizeBytes,
    } satisfies HistoryItem;
  });

  items.sort((a, b) => {
    const aTime = a.progress?.updatedAt ?? a.video.createdAt;
    const bTime = b.progress?.updatedAt ?? b.video.createdAt;
    return bTime - aTime;
  });

  return items;
}

export async function updateProgress(trackId: string, currentIndex: number): Promise<void> {
  await db.progress.put({
    trackId,
    currentIndex,
    updatedAt: Date.now(),
  });
}

export async function getLatestRecording(
  trackId: string,
  segmentIndex: number,
): Promise<RecordingRecord | undefined> {
  return db.recordings.get(buildRecordingId(trackId, segmentIndex));
}

export async function saveLatestRecording(params: {
  trackId: string;
  segmentIndex: number;
  blob: Blob;
  mimeType: string;
  durationMs: number;
}): Promise<RecordingRecord> {
  const record: RecordingRecord = {
    id: buildRecordingId(params.trackId, params.segmentIndex),
    trackId: params.trackId,
    segmentIndex: params.segmentIndex,
    blob: params.blob,
    mimeType: params.mimeType,
    durationMs: params.durationMs,
    updatedAt: Date.now(),
  };

  await db.recordings.put(record);
  return record;
}

export async function saveFreeRecording(params: {
  trackId: string;
  startSegmentIndex: number;
  endSegmentIndex: number;
  blob: Blob;
  mimeType: string;
  durationMs: number;
  playbackSpeed: number;
}): Promise<FreeRecordingRecord> {
  const now = Date.now();
  const record: FreeRecordingRecord = {
    id: `${params.trackId}:free:${now}`,
    trackId: params.trackId,
    startSegmentIndex: params.startSegmentIndex,
    endSegmentIndex: params.endSegmentIndex,
    blob: params.blob,
    mimeType: params.mimeType,
    durationMs: params.durationMs,
    playbackSpeed: params.playbackSpeed,
    createdAt: now,
  };
  await db.freeRecordings.put(record);
  return record;
}

export async function listVocabularyWords(params?: {
  trackId?: string;
  videoId?: string;
}): Promise<VocabularyRecord[]> {
  const { trackId, videoId } = params ?? {};

  if (trackId) {
    const entries = await db.vocabulary.where("trackId").equals(trackId).toArray();
    return entries.sort((a, b) => b.updatedAt - a.updatedAt);
  }

  if (videoId) {
    const entries = await db.vocabulary.where("videoId").equals(videoId).toArray();
    return entries.sort((a, b) => b.updatedAt - a.updatedAt);
  }

  return db.vocabulary.orderBy("updatedAt").reverse().toArray();
}

export async function saveVocabularyWord(params: {
  text: string;
  videoId: string;
  videoTitle: string;
  trackId: string;
  segmentIndex?: number;
  segmentText?: string;
}): Promise<{ record: VocabularyRecord; created: boolean }> {
  const word = cleanVocabularyText(params.text);
  const normalizedWord = normalizeVocabularyKey(params.text);

  if (!word || !normalizedWord) {
    throw new Error("Vocabulary word cannot be empty.");
  }

  const now = Date.now();
  const id = buildVocabularyId(params.trackId, normalizedWord);
  const existing = await db.vocabulary.get(id);

  const record: VocabularyRecord = {
    id,
    word,
    normalizedWord,
    videoId: params.videoId,
    videoTitle: params.videoTitle,
    trackId: params.trackId,
    segmentIndex: params.segmentIndex ?? existing?.segmentIndex,
    segmentText: params.segmentText ?? existing?.segmentText,
    createdAt: existing?.createdAt ?? now,
    updatedAt: now,
  };

  await db.vocabulary.put(record);
  return { record, created: !existing };
}

export async function deleteVocabularyWord(id: string): Promise<void> {
  await db.vocabulary.delete(id);
}

export async function clearAllData(): Promise<void> {
  await db.transaction(
    "rw",
    [
      db.videos,
      db.tracks,
      db.segments,
      db.progress,
      db.recordings,
      db.freeRecordings,
      db.vocabulary,
    ],
    async () => {
      await Promise.all([
        db.vocabulary.clear(),
        db.freeRecordings.clear(),
        db.recordings.clear(),
        db.progress.clear(),
        db.segments.clear(),
        db.tracks.clear(),
        db.videos.clear(),
      ]);
    },
  );
}
