import Dexie from "dexie";
import { db } from "@/features/storage/db";
import {
  buildIdCandidates,
  buildSegmentId,
  buildTrackId,
  trackMatchKey,
} from "@/features/storage/ids";
import type { SegmentDTO, TrackSummary } from "@/types/api";
import type {
  PracticeSessionRecord,
  ProgressRecord,
  SegmentRecord,
  TrackRecord,
  VideoRecord,
} from "@/types/models";

export { buildTrackId } from "@/features/storage/ids";
export {
  deleteRecordingsForVideo,
  getLatestRecording,
  getRecordedSegmentIndices,
  saveFreeRecording,
  saveLatestRecording,
} from "@/features/storage/recordings";
export {
  deleteVocabularyWord,
  listVocabularyWords,
  saveVocabularyWord,
} from "@/features/storage/vocabulary";
export { listStudySessions, saveStudySessionChunk } from "@/features/storage/studySessions";
export { clearAllData, deleteVideo, listHistory } from "@/features/storage/videos";

export function mapTracks(
  videoId: string,
  tracks: TrackSummary[],
  createdAt: number,
): TrackRecord[] {
  return tracks.map((track) => ({
    id: buildTrackId(videoId, track.token),
    videoId,
    token: track.token,
    languageCode: track.languageCode,
    label: track.label,
    isAutoGenerated: track.isAutoGenerated,
    createdAt,
  }));
}

export function mapSegments(trackId: string, segments: SegmentDTO[]): SegmentRecord[] {
  return segments.map((segment) => ({
    id: buildSegmentId(trackId, segment.index),
    trackId,
    index: segment.index,
    startMs: segment.startMs,
    endMs: segment.endMs,
    text: segment.text,
  }));
}

export async function saveImportBundle(params: {
  video: VideoRecord;
  tracks: TrackRecord[];
  targetTrackId: string;
  segments: SegmentRecord[];
}): Promise<{ effectiveTargetTrackId: string }> {
  const { video, tracks, targetTrackId, segments } = params;
  let effectiveTargetId = targetTrackId;

  await db.transaction(
    "rw",
    [
      db.videos,
      db.tracks,
      db.segments,
      db.progress,
      db.recordings,
      db.freeRecordings,
      db.vocabulary,
    ],
    async () => {
      await db.videos.put(video);

      const existingTracks = await db.tracks.where("videoId").equals(video.id).toArray();
      const existingByKey = new Map<string, TrackRecord>();
      for (const t of existingTracks) {
        existingByKey.set(trackMatchKey(t.languageCode, t.isAutoGenerated), t);
      }

      // Map new track IDs to old ones when a (languageCode, isAutoGenerated) match exists
      const idRemap = new Map<string, string>(); // newId -> oldId
      const matchedOldIds = new Set<string>();

      for (const newTrack of tracks) {
        const key = trackMatchKey(newTrack.languageCode, newTrack.isAutoGenerated);
        const existing = existingByKey.get(key);
        if (existing) {
          idRemap.set(newTrack.id, existing.id);
          matchedOldIds.add(existing.id);
        }
      }

      // Clean up orphaned tracks (exist in old set but no match in new set)
      for (const oldTrack of existingTracks) {
        if (!matchedOldIds.has(oldTrack.id)) {
          await db.segments.where("trackId").equals(oldTrack.id).delete();
          await db.recordings.where("trackId").equals(oldTrack.id).delete();
          await db.freeRecordings.where("trackId").equals(oldTrack.id).delete();
          await db.vocabulary.where("trackId").equals(oldTrack.id).delete();
          await db.progress.delete(oldTrack.id);
        }
      }

      // Delete old tracks, insert new ones with remapped IDs
      await db.tracks.where("videoId").equals(video.id).delete();
      const remappedTracks = tracks.map((t) => ({
        ...t,
        id: idRemap.get(t.id) ?? t.id,
      }));
      await db.tracks.bulkPut(remappedTracks);

      // Resolve the effective target track ID
      effectiveTargetId = idRemap.get(targetTrackId) ?? targetTrackId;

      // Replace segments for the target track only
      await db.segments.where("trackId").equals(effectiveTargetId).delete();
      if (segments.length > 0) {
        const remappedSegments = segments.map((s) => ({
          ...s,
          id: buildSegmentId(effectiveTargetId, s.index),
          trackId: effectiveTargetId,
        }));
        await db.segments.bulkPut(remappedSegments);
      }

      // Initialize progress only if none exists for this track
      const existingProgress = await db.progress.get(effectiveTargetId);
      if (!existingProgress) {
        await db.progress.put({
          trackId: effectiveTargetId,
          currentIndex: 0,
          updatedAt: Date.now(),
        });
      }
    },
  );

  return { effectiveTargetTrackId: effectiveTargetId };
}

export async function saveSegmentsForTrack(
  trackId: string,
  segments: SegmentRecord[],
): Promise<void> {
  await db.transaction("rw", db.segments, async () => {
    await db.segments.where("trackId").equals(trackId).delete();
    if (segments.length > 0) {
      await db.segments.bulkPut(segments);
    }
  });
}

export async function getPracticeSession(
  videoId: string,
  trackId: string,
): Promise<{
  video?: VideoRecord;
  track?: TrackRecord;
  tracks: TrackRecord[];
  segments: SegmentRecord[];
  progress?: ProgressRecord;
}> {
  const videoIdCandidates = buildIdCandidates(videoId);
  const trackIdCandidates = buildIdCandidates(trackId);

  const [videoCandidates, trackCandidates, tracks, progressCandidates] = await Promise.all([
    Promise.all(videoIdCandidates.map((candidate) => db.videos.get(candidate))),
    Promise.all(trackIdCandidates.map((candidate) => db.tracks.get(candidate))),
    db.tracks.where("videoId").anyOf(videoIdCandidates).toArray(),
    Promise.all(trackIdCandidates.map((candidate) => db.progress.get(candidate))),
  ]);

  const video = videoCandidates.find((candidate): candidate is VideoRecord => Boolean(candidate));
  const track =
    trackCandidates.find((candidate): candidate is TrackRecord => Boolean(candidate)) ??
    tracks.find((candidate) => trackIdCandidates.includes(candidate.id));
  const resolvedTrackId = track?.id ?? trackIdCandidates[0];
  const progress = progressCandidates.find((candidate): candidate is ProgressRecord =>
    Boolean(candidate),
  );

  const segments = await db.segments
    .where("[trackId+index]")
    .between([resolvedTrackId, Dexie.minKey], [resolvedTrackId, Dexie.maxKey])
    .sortBy("index");

  return {
    video,
    track,
    tracks,
    segments,
    progress,
  };
}

export async function updateProgress(trackId: string, currentIndex: number): Promise<void> {
  await db.progress.put({
    trackId,
    currentIndex,
    updatedAt: Date.now(),
  });
}

export async function listPracticeSessions(): Promise<PracticeSessionRecord[]> {
  return db.practiceSessions.orderBy("createdAt").reverse().toArray();
}
