import Dexie from "dexie";
import { db } from "@/features/storage/db";
import type { TrackSummary } from "@/types/api";
import type { HistoryItem, ProgressRecord, RecordingRecord, SegmentRecord, TrackRecord, VideoRecord } from "@/types/models";

export function buildTrackId(videoId: string, token: string): string {
  return `${videoId}:${token}`;
}

export function buildSegmentId(trackId: string, index: number): string {
  return `${trackId}:${index}`;
}

function buildRecordingId(trackId: string, segmentIndex: number): string {
  return `${trackId}:${segmentIndex}`;
}

function buildIdCandidates(value: string): string[] {
  const candidates = [value];
  let decoded = value;

  // Try decoding twice so both encoded and double-encoded IDs can resolve.
  for (let index = 0; index < 2; index += 1) {
    try {
      const next = decodeURIComponent(decoded);
      if (next === decoded) {
        break;
      }
      decoded = next;
      if (!candidates.includes(decoded)) {
        candidates.push(decoded);
      }
    } catch {
      break;
    }
  }

  return candidates;
}

export function mapTracks(videoId: string, tracks: TrackSummary[], createdAt: number): TrackRecord[] {
  return tracks.map((track) => ({
    id: buildTrackId(videoId, track.token),
    videoId,
    token: track.token,
    languageCode: track.languageCode,
    label: track.label,
    isAutoGenerated: track.isAutoGenerated,
    createdAt
  }));
}

export function mapSegments(trackId: string, segments: Array<{ index: number; startMs: number; endMs: number; text: string }>): SegmentRecord[] {
  return segments.map((segment) => ({
    id: buildSegmentId(trackId, segment.index),
    trackId,
    index: segment.index,
    startMs: segment.startMs,
    endMs: segment.endMs,
    text: segment.text
  }));
}

export async function saveImportBundle(params: {
  video: VideoRecord;
  tracks: TrackRecord[];
  targetTrackId: string;
  segments: SegmentRecord[];
}): Promise<void> {
  const { video, tracks, targetTrackId, segments } = params;

  await db.transaction("rw", [db.videos, db.tracks, db.segments, db.progress, db.recordings], async () => {
    await db.videos.put(video);

    const existingTracks = await db.tracks.where("videoId").equals(video.id).toArray();
    for (const track of existingTracks) {
      await db.segments.where("trackId").equals(track.id).delete();
      await db.recordings.where("trackId").equals(track.id).delete();
      await db.progress.delete(track.id);
    }

    await db.tracks.where("videoId").equals(video.id).delete();
    await db.tracks.bulkPut(tracks);

    await db.segments.where("trackId").equals(targetTrackId).delete();
    if (segments.length > 0) {
      await db.segments.bulkPut(segments);
    }

    const existingProgress = await db.progress.get(targetTrackId);
    if (!existingProgress) {
      await db.progress.put({
        trackId: targetTrackId,
        currentIndex: 0,
        updatedAt: Date.now()
      });
    }
  });
}

export async function saveSegmentsForTrack(trackId: string, segments: SegmentRecord[]): Promise<void> {
  await db.transaction("rw", db.segments, async () => {
    await db.segments.where("trackId").equals(trackId).delete();
    if (segments.length > 0) {
      await db.segments.bulkPut(segments);
    }
  });
}

export async function getPracticeSession(videoId: string, trackId: string): Promise<{
  video?: VideoRecord;
  track?: TrackRecord;
  tracks: TrackRecord[];
  segments: SegmentRecord[];
  progress?: ProgressRecord;
}> {
  const videoIdCandidates = buildIdCandidates(videoId);
  const trackIdCandidates = buildIdCandidates(trackId);

  const [videoCandidates, trackCandidates, tracks, progressCandidates] = await Promise.all([
    Promise.all(videoIdCandidates.map((candidate) => db.videos.get(candidate))),
    Promise.all(trackIdCandidates.map((candidate) => db.tracks.get(candidate))),
    db.tracks.where("videoId").anyOf(videoIdCandidates).toArray(),
    Promise.all(trackIdCandidates.map((candidate) => db.progress.get(candidate)))
  ]);

  const video = videoCandidates.find((candidate): candidate is VideoRecord => Boolean(candidate));
  const track =
    trackCandidates.find((candidate): candidate is TrackRecord => Boolean(candidate)) ??
    tracks.find((candidate) => trackIdCandidates.includes(candidate.id));
  const resolvedTrackId = track?.id ?? trackIdCandidates[0];
  const progress = progressCandidates.find((candidate): candidate is ProgressRecord => Boolean(candidate));

  const segments = await db.segments
    .where("[trackId+index]")
    .between([resolvedTrackId, Dexie.minKey], [resolvedTrackId, Dexie.maxKey])
    .sortBy("index");

  return {
    video,
    track,
    tracks,
    segments,
    progress
  };
}

export async function deleteVideo(videoId: string): Promise<void> {
  await db.transaction("rw", [db.videos, db.tracks, db.segments, db.progress, db.recordings], async () => {
    const tracks = await db.tracks.where("videoId").equals(videoId).toArray();
    for (const track of tracks) {
      await db.segments.where("trackId").equals(track.id).delete();
      await db.recordings.where("trackId").equals(track.id).delete();
      await db.progress.delete(track.id);
    }
    await db.tracks.where("videoId").equals(videoId).delete();
    await db.videos.delete(videoId);
  });
}

export async function deleteRecordingsForVideo(videoId: string): Promise<void> {
  await db.transaction("rw", [db.tracks, db.recordings], async () => {
    const tracks = await db.tracks.where("videoId").equals(videoId).toArray();
    for (const track of tracks) {
      await db.recordings.where("trackId").equals(track.id).delete();
    }
  });
}

export async function getRecordedSegmentIndices(trackId: string): Promise<Set<number>> {
  const recordings = await db.recordings.where("trackId").equals(trackId).toArray();
  return new Set(recordings.map((r) => r.segmentIndex));
}

export async function listHistory(): Promise<HistoryItem[]> {
  const [videos, tracks, progressItems, allSegments, allRecordings] = await Promise.all([
    db.videos.toArray(),
    db.tracks.toArray(),
    db.progress.toArray(),
    db.segments.toArray(),
    db.recordings.toArray()
  ]);

  const tracksByVideo = new Map<string, TrackRecord[]>();
  for (const track of tracks) {
    const list = tracksByVideo.get(track.videoId) ?? [];
    list.push(track);
    tracksByVideo.set(track.videoId, list);
  }

  const progressByTrack = new Map<string, ProgressRecord>();
  for (const item of progressItems) {
    progressByTrack.set(item.trackId, item);
  }

  const segmentCountByTrack = new Map<string, number>();
  for (const segment of allSegments) {
    segmentCountByTrack.set(segment.trackId, (segmentCountByTrack.get(segment.trackId) ?? 0) + 1);
  }

  const recordingCountByTrack = new Map<string, number>();
  const recordingSizeByTrack = new Map<string, number>();
  for (const recording of allRecordings) {
    recordingCountByTrack.set(recording.trackId, (recordingCountByTrack.get(recording.trackId) ?? 0) + 1);
    recordingSizeByTrack.set(recording.trackId, (recordingSizeByTrack.get(recording.trackId) ?? 0) + recording.blob.size);
  }

  const items = videos.map((video) => {
    const videoTracks = tracksByVideo.get(video.id) ?? [];

    let activeTrack: TrackRecord | undefined;
    let activeProgress: ProgressRecord | undefined;

    for (const track of videoTracks) {
      const progress = progressByTrack.get(track.id);
      if (!progress) {
        continue;
      }

      if (!activeProgress || progress.updatedAt > activeProgress.updatedAt) {
        activeProgress = progress;
        activeTrack = track;
      }
    }

    if (!activeTrack && videoTracks.length > 0) {
      activeTrack = videoTracks[0];
    }

    const segmentCount = activeTrack ? segmentCountByTrack.get(activeTrack.id) ?? 0 : 0;
    const recordingCount = activeTrack ? recordingCountByTrack.get(activeTrack.id) ?? 0 : 0;
    const recordingSizeBytes = activeTrack ? recordingSizeByTrack.get(activeTrack.id) ?? 0 : 0;

    return {
      video,
      activeTrack,
      progress: activeProgress,
      segmentCount,
      recordingCount,
      recordingSizeBytes
    } satisfies HistoryItem;
  });

  items.sort((a, b) => {
    const aTime = a.progress?.updatedAt ?? a.video.createdAt;
    const bTime = b.progress?.updatedAt ?? b.video.createdAt;
    return bTime - aTime;
  });

  return items;
}

export async function updateProgress(trackId: string, currentIndex: number): Promise<void> {
  await db.progress.put({
    trackId,
    currentIndex,
    updatedAt: Date.now()
  });
}

export async function getLatestRecording(trackId: string, segmentIndex: number): Promise<RecordingRecord | undefined> {
  return db.recordings.get(buildRecordingId(trackId, segmentIndex));
}

export async function saveLatestRecording(params: {
  trackId: string;
  segmentIndex: number;
  blob: Blob;
  mimeType: string;
  durationMs: number;
}): Promise<RecordingRecord> {
  const record: RecordingRecord = {
    id: buildRecordingId(params.trackId, params.segmentIndex),
    trackId: params.trackId,
    segmentIndex: params.segmentIndex,
    blob: params.blob,
    mimeType: params.mimeType,
    durationMs: params.durationMs,
    updatedAt: Date.now()
  };

  await db.recordings.put(record);
  return record;
}

export async function clearAllData(): Promise<void> {
  await db.transaction("rw", [db.videos, db.tracks, db.segments, db.progress, db.recordings], async () => {
    await Promise.all([
      db.recordings.clear(),
      db.progress.clear(),
      db.segments.clear(),
      db.tracks.clear(),
      db.videos.clear()
    ]);
  });
}
