import assert from "node:assert/strict";
import test from "node:test";
import {
  createImportBundleFromExtensionPayload,
  parseExtensionImportMessage,
} from "@/features/import/extensionImport";

function makePayload() {
  return {
    version: 1 as const,
    source: "shadowing-space-extension" as const,
    exportedAt: "2026-04-15T13:00:00.000Z",
    video: {
      videoId: "FRI78tq9Eik",
      title: "  Daily Speaking Drill  ",
      thumbnailUrl: "https://i.ytimg.com/vi/FRI78tq9Eik/hqdefault.jpg",
    },
    track: {
      languageCode: "en",
      label: " English ",
      isAutoGenerated: false,
      originTrackId: ".en",
    },
    segments: [
      {
        startMs: 1_800,
        endMs: 3_000,
        text: "  How are you?  ",
      },
      {
        startMs: 0,
        endMs: 1_500,
        text: " Hello there. ",
      },
    ],
  };
}

test("createImportBundleFromExtensionPayload maps a valid payload into deterministic local records", () => {
  const bundle = createImportBundleFromExtensionPayload(makePayload(), 1_234_567_890);

  assert.equal(bundle.video.id, "FRI78tq9Eik");
  assert.equal(bundle.video.title, "Daily Speaking Drill");
  assert.equal(bundle.video.youtubeVideoId, "FRI78tq9Eik");
  assert.equal(bundle.video.createdAt, 1_234_567_890);

  assert.equal(bundle.tracks.length, 1);
  assert.equal(bundle.tracks[0]?.languageCode, "en");
  assert.equal(bundle.tracks[0]?.label, "English");
  assert.equal(bundle.tracks[0]?.isAutoGenerated, false);
  assert.equal(bundle.tracks[0]?.token, "ext-v1:en:manual:.en");

  assert.equal(bundle.targetTrackId, "FRI78tq9Eik:ext-v1:en:manual:.en");
  assert.deepEqual(
    bundle.segments.map((segment) => segment.text),
    ["Hello there.", "How are you?"],
  );
  assert.deepEqual(
    bundle.segments.map((segment) => ({
      id: segment.id,
      trackId: segment.trackId,
      index: segment.index,
      startMs: segment.startMs,
      endMs: segment.endMs,
    })),
    [
      {
        id: "FRI78tq9Eik:ext-v1:en:manual:.en:0",
        trackId: "FRI78tq9Eik:ext-v1:en:manual:.en",
        index: 0,
        startMs: 0,
        endMs: 1_500,
      },
      {
        id: "FRI78tq9Eik:ext-v1:en:manual:.en:1",
        trackId: "FRI78tq9Eik:ext-v1:en:manual:.en",
        index: 1,
        startMs: 1_800,
        endMs: 3_000,
      },
    ],
  );
});

test("createImportBundleFromExtensionPayload rejects malformed or empty extension payloads", () => {
  assert.throws(
    () =>
      createImportBundleFromExtensionPayload({
        ...makePayload(),
        segments: [{ startMs: 100, endMs: 100, text: "oops" }],
      }),
    /extension import payload/i,
  );

  assert.throws(
    () =>
      createImportBundleFromExtensionPayload({
        ...makePayload(),
        track: { ...makePayload().track, languageCode: "" },
      }),
    /extension import payload/i,
  );
});

test("parseExtensionImportMessage returns payload only for the extension handoff message", () => {
  const payload = makePayload();

  const parsed = parseExtensionImportMessage({
    type: "shadowing-space-extension/import",
    payload,
  });

  assert.ok(parsed);
  assert.equal(parsed.video.title, "Daily Speaking Drill");
  assert.equal(parsed.track.label, "English");
  assert.equal(parsed.segments[0]?.text, "How are you?");

  assert.equal(
    parseExtensionImportMessage({
      type: "something-else",
      payload,
    }),
    null,
  );
});
