import assert from "node:assert/strict";
import test from "node:test";
import { parseExtensionPayloadFromText } from "@/features/import/fileImport";

function makePayloadText() {
  return JSON.stringify({
    version: 1,
    source: "shadowing-space-extension",
    exportedAt: "2026-04-16T05:00:00.000Z",
    video: { videoId: "FRI78tq9Eik", title: "Test" },
    track: { languageCode: "en", label: "English", isAutoGenerated: false, originTrackId: ".en" },
    segments: [{ startMs: 0, endMs: 1000, text: "Hello." }],
  });
}

test("parseExtensionPayloadFromText returns the payload for a well-formed JSON file", () => {
  const result = parseExtensionPayloadFromText(makePayloadText());
  assert.ok(result);
  assert.equal(result.video.videoId, "FRI78tq9Eik");
  assert.equal(result.segments.length, 1);
});

test("parseExtensionPayloadFromText throws a clear message for invalid JSON", () => {
  assert.throws(() => parseExtensionPayloadFromText("{not json"), /could not parse.*json/i);
});

test("parseExtensionPayloadFromText throws a clear message when the schema is wrong", () => {
  const bad = JSON.stringify({
    version: 1,
    source: "wrong-source",
    exportedAt: "2026-04-16T05:00:00.000Z",
    video: { videoId: "x", title: "t" },
    track: { languageCode: "en", label: "English", isAutoGenerated: false },
    segments: [{ startMs: 0, endMs: 1000, text: "Hello" }],
  });
  assert.throws(() => parseExtensionPayloadFromText(bad), /shadowing space/i);
});

test("parseExtensionPayloadFromText trims leading whitespace and BOM", () => {
  const text = "\ufeff  \n" + makePayloadText();
  const result = parseExtensionPayloadFromText(text);
  assert.ok(result);
  assert.equal(result.video.videoId, "FRI78tq9Eik");
});
